(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1490151721972", id:"HTML5rastershad"},
		{src:"images/Transfer336x280.jpg?1490151721972", id:"Transfer336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Transfer336x280 = function() {
	this.initialize(img.Transfer336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,166);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTC9IAAgHIgEAAQgIAAgEgDQgEgFAAgGIABgHIAGAAIgBAGQAAAJAKgBIAEAAIAAgOIAGAAIAAAOIAmAAIAAAHIgmAAIAAAHgAgNCVQgHgGAAgJQAAgKAHgHQAHgFAIgBIADABIAAAkQAPgBAAgPQAAgIgGgGIAEgFQAIAIAAALQAAAKgGAHQgHAGgLAAQgIABgHgHgAgOCGQAAAFAEAFQAEADAGABIAAgdQgOACAAANgAgOBfQgGgGAAgJQAAgKAKgIIgcAAIAAgGIA/AAIAAAGIgJAAQAKAHAAALQAAAJgGAGQgHAIgLgBQgJABgHgIgAgJBDQgFAFAAAHQAAAHAFAFQAFAEAGAAIAAAAQAIAAAFgFQAFgFAAgGQAAgHgFgFQgFgFgIAAIAAAAQgGAAgFAFgAgNAkQgHgGAAgKQAAgKAHgGQAHgEAIAAIADAAIAAAkQAHgBAEgFQAEgFAAgFQAAgJgGgHIAEgDQAIAHAAAMQAAAJgGAHQgHAGgLAAQgIABgHgHgAgOAUQAAAGAEAEQAEAEAGACIAAgfQgOACAAANgAgTgMIAAgHIAMAAQgNgGAAgNIAHAAIAAABQAAAIAGAFQAGAGAIgBIASAAIAAAHgAAAgwQgCgFAAgJQAAgFACgKIgBAAQgNABAAAOQAAAHAEAGIgGACQgEgHAAgJQAAgLAFgEQAFgFAJAAIAaAAIAAAGIgHAAQAIAGAAAMQAAAGgDAFQgFAGgGAAQgIAAgEgGgAACg/QAAAOAJAAQAKAAAAgMQAAgHgEgEQgDgEgGgBIgEAAQgCAIAAAGgAgmhiIAAgHIA/AAIAAAHgAgmh6IAAgHIA/AAIAAAHgAgTiUIAlgRIglgPIAAgHIAuATQANAGAAAKQAAAFgCAFIgGgDQACgDAAgEQAAgGgJgDIgsAVg");
	this.shape.setTransform(44,-24.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AglFZIAAgIIAIAAIAAAIgAgTFZIAAgHIAsAAIAAAHgAgTFBIAAgHIAIAAQgJgFAAgKQAAgJAEgFQAGgEAIAAIAbAAIAAAHIgZAAQgOAAAAANQAAAGAEAEQAEADAGAAIAZAAIAAAHgAAOEKQAGgHAAgJQAAgKgHAAQgGABgCALQgFAQgHgBQgGAAgEgEQgDgEAAgHQgBgJAGgIIAFAEQgFAGAAAHQABAJAGAAQAFAAADgMQADgPAJAAQAGAAAFAFQADAFAAAGQAAALgHAJgAgTDeIAAgHIAZAAQAOAAAAgNQAAgGgEgEQgEgEgHAAIgYAAIAAgGIAsAAIAAAGIgIAAQAJAGAAAKQAAAIgFAGQgFAEgJAAgAgTCmIAAgHIALAAQgMgGAAgNIAHAAIAAAAQAAAJAFAEQAHAGAIAAIASAAIAAAHgAgOCAQgGgGAAgKQAAgKAGgHQAIgFAIAAIADAAIAAAlQAHgBAEgEQAEgFAAgGQAAgIgGgHIADgEQAJAIAAALQAAAKgHAHQgGAGgLAAQgIAAgIgGgAgPBwQAAAGAFAEQAEAEAGABIAAgeQgPACAAANgAgOBKQgHgGABgJQAAgLAKgHIgcAAIAAgHIA/AAIAAAHIgJAAQAKAGAAAMQAAAJgHAGQgGAHgLAAQgJAAgHgHgAgJAtQgFAFAAAIQAAAGAFAFQAFAFAFAAIABAAQAIgBAFgFQAFgEAAgGQAAgIgFgFQgGgEgHAAIgBAAQgFAAgFAEgAgmgHIAAgGIAcAAQgKgIAAgKQgBgKAHgGQAHgHAIAAIABAAQALAAAGAHQAHAGAAAKQAAALgKAHIAJAAIAAAGgAgJgpQgFAEAAAHQAAAHAFAEQAFAFAFABIABAAQAHgBAGgFQAFgEAAgHQAAgHgFgEQgFgGgIAAQgGAAgFAGgAgThDIAkgRIgkgPIAAgIIAtAUQAOAFAAAKQgBAHgCADIgFgCQABgDABgEQAAgGgJgEIgsAWgAgTiRIAAgHIAIAAQgJgFAAgKQAAgJAEgFQAGgEAIAAIAbAAIAAAHIgZAAQgOAAAAANQAAAGAEAEQAEADAGAAIAZAAIAAAHgAgOjMQgGgGAAgLQgBgKAJgIIAEAEQgGAIgBAHQAAAGAGAFQAFAFAFAAIABAAQAHAAAGgFQAFgFAAgHQAAgHgHgIIAEgEQAJAIAAALQAAALgHAGQgHAHgKAAQgIAAgIgHgAgTj7IAAgGIAZAAQAOAAAAgOQAAgFgEgFQgEgDgHAAIgYAAIAAgHIAsAAIAAAHIgIAAQAJAGAAAJQAAATgTgBgAgClDQAAgGACgIIgBAAQgNAAAAANQAAAHAEAIIgGABQgEgIAAgIQAAgKAFgGQAEgEAKAAIAaAAIAAAHIgHAAQAIAFAAAMQAAAHgDAFQgFAFgHAAQgNAAAAgUgAABlEQAAAOAKAAQAKAAgBgMQAAgHgDgEQgEgFgFABIgEAAQgDAGAAAHg");
	this.shape_1.setTransform(54.1,-28.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40,-63,18.2,69.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAQIAAgfIAdAAIAAAfg");
	this.shape.setTransform(172.7,43.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXA8QgSgIgIgGIANgTQAKAHALAEQALAEAHAAQAKAAAFgEQAFgDAAgHIAAAAQAAgHgIgEQgFgCgNgFQgUgGgHgEQgGgEgEgGQgDgGAAgJQAAgJADgIQAEgHAGgFQAGgFAJgCQAIgDAHAAQAMAAANAEQAMAEAKAGIgLAVQgKgGgJgDQgKgDgHAAQgHAAgFADQgEAEAAAGIAAAAQAAAGAJAFIARAHIAPAFIAMAFQAGAFADAFQAEAHAAAIIAAAAQAAAKgEAIQgEAHgGAFQgGAFgJADQgJACgKAAQgLAAgOgFg");
	this.shape_1.setTransform(163.3,38.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAJgJANgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgJAJgMAFQgRAGgJAAgAgPgkQgHADgFAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGQAEgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgFgGgIgDQgGgDgIAAQgIAAgHADg");
	this.shape_2.setTransform(149.6,38.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_3.setTransform(134.5,38.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbBUQgLgEgIgJQgIgIgFgMIgEgOIgBgOIAAgBQAAgKAFgQQAFgMAIgJQAIgIALgEQAKgFAMAAQAFAAAHACQAGACAGADQAJAGAIAKIAAhEIAdAAIAACtIgdAAIAAgVQgIALgJAFQgGAEgGACQgHABgFAAQgLAAgLgEgAgMgOQgHADgFAFQgFAGgDAFQgDAIAAAJIAAABQAAAJADAHQADAIAFAFQAFAFAHADQAGADAGAAQAHAAAHgDQAGgDAFgFQAGgGACgHQAEgIAAgIIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgHgDgHAAQgGAAgGACg");
	this.shape_4.setTransform(118.9,36.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNBWIAAh8IAbAAIAAB8gAgOg5IAAgcIAdAAIAAAcg");
	this.shape_5.setTransform(107.8,36.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLA/Ig1h9IAgAAIAgBbIAihbIAfAAIg0B9g");
	this.shape_6.setTransform(97.2,38.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_7.setTransform(77.8,37.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgcA+QgIgCgHgFQgFgFgFgHQgDgIAAgJIAAgBQAAgKAEgIQADgHAIgDQAGgGAKgCQAJgDALAAQAOAAATAFIAAgCQAAgGgBgFQgCgGgFgDQgDgDgHgDQgFgBgFAAQgKgBgKADQgHABgKAFIgIgYQAMgFAJgCQANgDAMAAQAOAAALADQAKAEAHAHQAHAHADAKQAEAKAAANIAABIIgdAAIAAgPQgHAIgKAFQgMAFgKAAQgJAAgIgDgAgKAGQgGABgDACQgEADgCAEQgCAEAAAEIAAAAQAAAJAHAGQAHAEALAAQAFAAAFgBQAHgCAEgEQAFgDADgGQACgEAAgHIAAgHQgSgEgLAAQgFgBgFACg");
	this.shape_8.setTransform(65.7,38.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGBAIgMgEQgLgFgJgJQgKgJgFgMQgEgMAAgNIAAAAQAAgMAEgMQAFgMAKgJQAJgJALgFIANgEQAFgCAHAAQAJAAAHACIANAEQAJAEAMAMIgSAUQgHgIgHgEQgIgEgKAAQgHAAgHADQgGADgFAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAIQAEAHAEAGQAFAFAHADQAGADAIAAQAJAAAJgEQAHgEAIgHIARARQgNANgIAEQgHADgHACQgHACgJAAg");
	this.shape_9.setTransform(52.3,38.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgfBQQgPgEgMgHIALgWQALAGAKAEQAMADAMAAQAIAAAHgCQAIgDAFgFQAFgFADgHQACgHAAgKIAAgKQgLANgHAEQgGADgGACQgGACgGAAQgMAAgKgEQgKgEgIgIQgJgIgEgLQgFgJAAgOIAAAAQAAgJAFgQQAEgLAJgIQAIgIAKgEQAKgEAMAAQAGAAAGACIAMAFQAKAFAIAKIAAgTIAdAAIAABjQAAAQgEAMQgEAMgIAIIgKAHIgMAFQgTAFgJAAQgQAAgOgEgAgNg4QgGADgFAEQgFAFgDAGQgDAHAAAIIAAAAQAAAIADAGQADAHAFACQAFAFAGADQAHACAGAAQAHAAAHgCQAGgDAFgFQAGgCACgHQAEgGAAgIIAAAAQAAgIgEgGQgCgHgGgEQgFgFgGgDQgHgCgHAAQgGAAgHACg");
	this.shape_10.setTransform(29.8,40.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAJQADAJAAALIAABOg");
	this.shape_11.setTransform(14.7,38.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNBWIAAh8IAbAAIAAB8gAgOg5IAAgcIAdAAIAAAcg");
	this.shape_12.setTransform(3.8,36.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAbBXIAAhIQAAgHgCgGQgBgEgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGACgDAEQgEAFgCADQgDAHAAAHIAABHIgcAAIAAitIAcAAIAABEQAIgKAIgGQAFgDAGgBQAEgDAHAAQALAAAIAEQAJADAFAHQAGAHADAJQADAIAAAKIAABQg");
	this.shape_13.setTransform(-7,36.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgFBAIgNgEQgLgFgKgJQgJgJgFgMQgEgMAAgNIAAAAQAAgMAEgMQAFgMAJgJQAKgJALgFIANgEQAFgCAGAAQAKAAAHACIAOAEQAHAEANAMIgSAUQgHgIgHgEQgJgEgKAAQgGAAgGADQgHADgFAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAIQAEAHAEAGQAGAFAHADQAFADAIAAQAKAAAIgEQAHgEAHgHIASARQgNANgIAEQgGADgIACQgHACgKAAg");
	this.shape_14.setTransform(-21.2,38.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_15.setTransform(-33.2,37.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgcA+QgIgCgHgFQgGgFgEgHQgDgIAAgJIAAgBQAAgKAEgIQADgHAIgDQAGgGAKgCQAJgDALAAQAOAAATAFIAAgCQAAgGgCgFQgBgGgFgDQgDgDgHgDQgFgBgFAAQgLgBgJADQgHABgKAFIgIgYQAMgFAJgCQANgDAMAAQAOAAALADQAKAEAHAHQAHAHADAKQAEAKAAANIAABIIgdAAIAAgPQgHAIgKAFQgMAFgKAAQgJAAgIgDgAgKAGQgGABgDACQgEADgCAEQgCAEAAAEIAAAAQAAAJAHAGQAHAEALAAQAFAAAFgBQAHgCAEgEQAFgDACgGQADgEAAgHIAAgHQgRgEgMAAQgFgBgFACg");
	this.shape_16.setTransform(-45.3,38.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAcA/IgchUIgbBUIgaAAIgph9IAeAAIAZBVIAchWIAXAAIAcBWIAahVIAdAAIgpB9g");
	this.shape_17.setTransform(-62.4,38.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_18.setTransform(-87.1,38.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABDBAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFACgDAEQgEAEgCAGQgCAGAAAIIAABFIgbAAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFADgDAEQgEAEgCAGQgCAGAAAHIAABFIgdAAIAAh8IAdAAIAAATQAHgKAIgFQAFgEAGgBQAGgCAHAAQAGAAAGACIALAEQAEADACAEIAGAJQAJgLAKgFIALgEQAGgCAHAAQALAAAIADQAIADAGAHQAGAGADAJQADAJAAALIAABPg");
	this.shape_19.setTransform(-105.7,38.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgdA8QgJgDgGgGQgFgHgDgJQgDgIAAgMIAAhOIAdAAIAABGQAAAHABAGQACAGAEAEQADADAFACQAFACAGABQAFgBAFgCQAGgCADgDQAEgFACgFQACgGAAgIIAAhFIAdAAIAAB8IgdAAIAAgTQgHAKgIAGIgLAEQgEACgHAAQgLAAgIgEg");
	this.shape_20.setTransform(-124.6,39);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXA8QgSgIgIgGIANgTQAKAHALAEQAKAEAIAAQAJAAAGgEQAFgDAAgHIAAAAQAAgHgIgEQgFgCgNgFQgTgGgIgEQgGgEgEgGQgDgGAAgJQAAgJADgIQAEgHAHgFQAGgFAHgCQAJgDAHAAQAMAAANAEQAMAEAKAGIgMAVQgJgGgJgDQgJgDgIAAQgHAAgEADQgFAEAAAGIAAAAQAAAGAIAFIASAHIAPAFIAMAFQAGAFADAFQAEAHAAAIIAAAAQAAAKgEAIQgEAHgGAFQgGAFgJADQgJACgKAAQgLAAgOgFg");
	this.shape_21.setTransform(-138.1,38.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_22.setTransform(-151.2,38.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAkBTIgng6IgBAAIgkAAIAAA6IgeAAIAAilIBJAAQALgBARAFQANAEAIAIQAGAHAEAJQAEAKAAAKIAAABQAAAKgDAJQgDAIgGAEQgFAHgHAEQgIAEgIADIAtA/gAgoAAIApAAQAIAAAGgBQAHgCAEgEQAFgEACgFQADgFAAgGIAAgBQAAgGgDgGQgCgFgFgEQgEgDgGgCQgHgBgIAAIgpAAg");
	this.shape_23.setTransform(-166.5,36.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgPAQIAAgfIAfAAIAAAfg");
	this.shape_24.setTransform(86.9,19.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgXA8QgSgIgIgGIANgTQAKAHALAEQAKAEAIAAQAKAAAFgEQAFgDAAgHIAAAAQAAgHgJgEQgDgCgOgFQgUgGgHgEQgGgEgEgGQgDgGAAgJQAAgJADgIQAEgHAGgFQAHgFAIgCQAIgDAIAAQALAAAMAEQANAEAKAGIgLAVQgKgGgJgDQgKgDgHAAQgHAAgFADQgEAEAAAGIAAAAQAAAGAJAFIASAHIANAFIANAFQAGAFADAFQAEAHAAAIIAAAAQAAAKgEAIQgDAHgHAFQgGAFgJADQgIACgKAAQgMAAgOgFg");
	this.shape_25.setTransform(77.5,14.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbBUQgLgEgIgJQgIgIgFgMIgEgOIgBgOIAAgBQAAgKAFgQQAFgMAIgJQAIgIALgEQAKgFAMAAQAFAAAHACQAGACAGADQAJAGAIAKIAAhEIAdAAIAACtIgdAAIAAgVQgIALgJAFQgGAEgGACQgHABgFAAQgLAAgLgEgAgMgOQgHADgFAFQgFAGgDAFQgDAIAAAJIAAABQAAAJADAHQADAIAFAFQAFAFAHADQAGADAGAAQAHAAAHgDQAGgDAFgFQAGgGACgHQAEgIAAgIIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgHgDgHAAQgGAAgGACg");
	this.shape_26.setTransform(63.3,12.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAJQADAJAAALIAABOg");
	this.shape_27.setTransform(48.2,14.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdA8QgJgDgGgGQgFgHgDgIQgDgKAAgLIAAhOIAdAAIAABGQAAAHABAGQACAGAEAEQADAEAFACQAFACAGAAQAFAAAFgCQAGgCADgEQAEgFACgFQACgHAAgHIAAhFIAdAAIAAB9IgdAAIAAgUQgHAKgIAFIgLAGQgEABgHAAQgLAAgIgEg");
	this.shape_28.setTransform(33.2,15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgWBYIAAhkIgQAAIAAgYIAQAAIAAgJQAAgLADgIQADgIAFgFQAFgFAGgCQAGgDAJAAQANAAALADIAAAZQgJgDgIAAQgIAAgFAEQgEAFAAAKIAAAHIAiAAIAAAYIghAAIAABkg");
	this.shape_29.setTransform(21.6,12.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_30.setTransform(5.3,14.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_31.setTransform(-7.4,14.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgWBYIAAhkIgQAAIAAgYIAQAAIAAgJQAAgLADgIQADgIAFgFQAFgFAGgCQAGgDAJAAQANAAALADIAAAZQgJgDgIAAQgIAAgFAEQgEAFAAAKIAAAHIAiAAIAAAYIghAAIAABkg");
	this.shape_32.setTransform(-18.9,12.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgXA8QgSgIgIgGIANgTQAKAHALAEQALAEAIAAQAIAAAGgEQAFgDAAgHIAAAAQAAgHgJgEQgEgCgNgFQgTgGgIgEQgGgEgDgGQgEgGAAgJQAAgJAEgIQADgHAHgFQAFgFAIgCQAJgDAHAAQAMAAAMAEQAMAEALAGIgMAVQgJgGgJgDQgJgDgIAAQgGAAgFADQgFAEAAAGIAAAAQAAAGAIAFIATAHIANAFIANAFQAGAFADAFQAEAHAAAIIAAAAQAAAKgEAIQgEAHgGAFQgGAFgJADQgJACgJAAQgMAAgOgFg");
	this.shape_33.setTransform(-29.8,14.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAJQADAJAAALIAABOg");
	this.shape_34.setTransform(-43,14.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgcA/QgIgDgGgFQgHgFgDgHQgEgIAAgJIAAgBQAAgJAEgJQADgHAIgEQAHgFAJgDQAJgCALAAQAOAAAUAFIAAgCQAAgHgCgEQgCgFgFgEQgEgEgFgCQgGgCgGAAQgKABgJACQgHACgKADIgIgXQAMgFAKgCQAMgDANAAQANAAALAEQAKADAHAHQAHAHAEAKQADAJAAANIAABKIgdAAIAAgQQgHAIgKAFQgMAFgKAAQgJAAgIgCgAgLAGQgEABgFADQgDACgCAEQgCADAAAFIAAAAQAAAKAHAFQAHAEAKAAQAFAAAHgCQAGgCAFgDQAEgDADgFQACgGAAgGIAAgGQgSgGgLAAQgFABgGABg");
	this.shape_35.setTransform(-57.9,14.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_36.setTransform(-69,14.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgNBUIAAiLIg2AAIAAgbICHAAIAAAbIg2AAIAACLg");
	this.shape_37.setTransform(-82.3,12.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-347.9,0,696,52);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("EgoTAHzIAAvmMBQnAAAIAAPmg");
	this.shape.setTransform(432,50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(174,0,516,100);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgYA/QgMgDgJgGIAIgRQAIAFAJADQAJACAKAAQAFAAAGgCQAGgBAEgEQAEgEACgGQADgGAAgHIAAgIQgJAKgGADQgEADgGABQgEABgFAAQgJAAgIgDQgIgDgGgGQgHgGgEgJQgDgHAAgLIAAAAQAAgHADgNQAEgIAHgHQAGgGAIgDQAIgDAJAAQAFAAAFABQAFABAEADQAIAEAGAIIAAgPIAXAAIAABOQAAAMgDAKQgDAJgGAHIgIAGIgKAEQgPADgHAAQgMAAgLgDgAgKgsQgFACgEAEIgGAIQgCAGAAAGIAAAAQAAAGACAFQACAFAEACQAEAEAFACQAFACAFAAQAFAAAGgCQAFgCAEgEQAEgCACgFQADgFAAgGIAAAAQAAgGgDgFQgCgFgEgEQgEgEgFgCQgGgCgFAAQgFAAgFACg");
	this.shape.setTransform(100.2,13.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AAWAzIAAg3QAAgGgCgFQgBgEgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgBAEAAAGIAAA3IgYAAIAAhjIAYAAIAAAQQAFgIAGgEIAJgEQADgCAFAAQAJAAAHADQAGADAFAFQAEAFADAHQADAHgBAJIAAA+g");
	this.shape_1.setTransform(88.3,12.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_2.setTransform(79.7,10.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AAUBFIgdgsIgNAPIAAAdIgYAAIAAiJIAYAAIAABRIAngrIAcAAIgoAnIAqA8g");
	this.shape_3.setTransform(72.1,10.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AAVAzIAAg3QABgGgCgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBAFQgCAEAAAGIAAA3IgWAAIAAhjIAWAAIAAAQQAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAGADAFAFQAFAFACAHQACAHABAJIAAA+g");
	this.shape_4.setTransform(60.1,12.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgWAxQgGgBgFgFQgFgEgDgFQgDgGAAgHQAAgJADgHQADgFAGgDQAFgDAHgDQAIgCAIAAQALAAAPAFIAAgDQABgEgCgFQgCgEgDgCQgDgDgEgCQgGgBgDAAQgIAAgHACIgOAFIgGgTQAJgEAIgCQAJgDAKABQALAAAIACQAJADAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAHgIAEQgJADgIAAQgHAAgHgCgAgIAEIgHADQgDADgCADQgBACAAAEIAAABQAAAGAGAFQAFADAIAAQAEAAAFgBIAIgEQAEgDACgEQACgEAAgFIAAgGQgOgEgJAAIgIABg");
	this.shape_5.setTransform(48.3,12.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("Ag2BCIAAiDIA6AAQALAAAJADQAJADAFAFQAFAFACAFQACAGAAAHQAAAGgBAFQgBAFgDADQgFAHgJAEIALACIAIAHQAEAEACAFQACAGAAAGIAAABQAAAIgDAHQgEAHgGAFQgHAEgJACQgJADgLAAgAgfAtIAlAAQAGAAAFgBQAEgBAEgCQADgCABgEQADgEAAgEIAAgBQAAgEgCgDIgFgFQgDgDgGgBIgMgBIgjAAgAgfgJIAfAAIAJgBQAFgBADgCQAEgDACgDQABgEAAgEIAAAAQAAgFgBgDQgCgCgDgCQgDgDgFgBQgEgBgFgBIggAAg");
	this.shape_6.setTransform(36.6,10.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKAEgJQADgJAGgIQAIgHAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAGAIIAJAEQAFACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgLADIgOACQgJAAgJgEgAAZgFQAAgHgDgEQgBgFgDgDQgDgEgFgCQgFgCgFAAQgDAAgFACQgFACgDADIgGAJIgCALIAxAAIAAAAg");
	this.shape_7.setTransform(17.9,12.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgKBFIAAiJIAVAAIAACJg");
	this.shape_8.setTransform(9.5,10.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_9.setTransform(4.1,10.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgFBEQgFgBgEgCQgHgFgGgIIAAAQIgXAAIAAiJIAXAAIAAA3QAGgJAHgEIAKgEQAEgCAFAAQAJAAAIAEQAIADAHAHQAHAHADAJQAEAMAAAIIAAABIgBAMIgDAKQgDAJgHAHQgGAHgJADQgIAEgJAAQgFAAgFgCgAgKgKQgFACgEAEQgEAEgDAEQgCAGAAAHIAAABQAAAHACAGQADAGAEAEQAEAEAFADQAGACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQACgGAAgHIAAgBQAAgHgCgGQgCgEgEgEQgEgEgGgCQgFgDgFAAQgEAAgGADg");
	this.shape_10.setTransform(-4.7,10.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgKAyIgKgCQgKgEgHgHQgHgIgEgJIgDgJIgBgLIAAAAQAAgGAEgNQAEgJAHgIQAHgHAKgEIALgDIAJgBQAHAAAOAEQAKAEAHAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAKQgEAJgIAIQgHAHgKAEQgNAEgHAAgAgLgdQgGADgEAEQgEAFgCAGQgCAGAAAFIAAAAQAAAGACAGQADAGAEAEQAEAFAFADQAGACAFAAQAGAAAGgCQAFgDAEgFQAFgEABgGQADgFAAgHIAAAAQAAgFgDgGQgBgGgFgEQgEgFgGgCQgFgDgGAAQgFAAgGACg");
	this.shape_11.setTransform(-17.5,12.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AApBCIAAhdIgpA8IAAAAIgpg8IAABdIgXAAIAAiDIAZAAIAnA/IAog/IAZAAIAACDg");
	this.shape_12.setTransform(-32,10.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgVBCQgJgDgGgHQgHgHgDgJIgDgKIgBgMIAAgBQAAgIADgMQAEgJAHgHQAGgHAJgDQAIgEAJAAQAEAAAFACIAKAEQAHAEAGAIIAAg2IAXAAIAACJIgXAAIAAgRQgGAJgHAEQgFADgFABQgFACgEAAQgJAAgIgEgAgKgKQgFACgEAEQgEAEgCAEQgCAGAAAHIAAABQAAAHACAGQACAGAEAEQAEAEAGADQAFACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQADgGAAgHIAAgBQAAgHgDgGQgCgEgEgEQgEgEgFgCQgGgDgFAAQgEAAgGADg");
	this.shape_13.setTransform(-52.5,10.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AAVAzIAAg3QAAgGgBgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBAFQgCAEAAAGIAAA3IgWAAIAAhjIAWAAIAAAQQAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAHADAEAFQAFAFACAHQACAHABAJIAAA+g");
	this.shape_14.setTransform(-64.4,12.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgXAwQgGgDgGgFQgEgFgDgHQgCgHAAgJIAAg+IAYAAIAAA3QgBAGACAFQABAEADAEQADADADABQAEACAFAAIAIgCQAEgBADgEQADgDABgEQADgFAAgGIAAg3IAWAAIAABjIgWAAIAAgQQgGAIgHAFQgEACgFABQgDACgFAAQgJAAgGgDg");
	this.shape_15.setTransform(-76.3,12.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgKAyIgKgCQgJgEgIgHQgHgIgEgJIgDgJIgBgLIAAAAQAAgGAEgNQAEgJAHgIQAIgHAJgEIAKgDIAKgBQAHAAAOAEQAKAEAHAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAKQgEAJgHAIQgIAHgJAEQgOAEgHAAgAgLgdQgGADgEAEQgEAFgCAGQgCAGAAAFIAAAAQAAAGACAGQADAGAEAEQADAFAGADQAGACAFAAQAHAAAFgCQAFgDAFgFQADgEACgGQADgFAAgHIAAAAQAAgFgDgGQgCgGgDgEQgFgFgFgCQgHgDgFAAQgGAAgFACg");
	this.shape_16.setTransform(-88.3,12.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgJBDQgIgCgHgDQgHgCgGgEQgHgEgGgGIAPgQQAFAGAOAGQAFADAFABIAKABIAKgBQAEgBADgDQAEgBABgEQACgDAAgDIAAgBQAAgDgCgDIgEgGIgJgEIgNgEIgTgGQgIgDgGgCQgGgFgDgGQgCgHAAgJIAAAAQAAgJADgHQADgHAGgFQAGgFAJgDQAIgDAJAAIAMABIAOADQAHADAOAKIgMARQgJgGgJgEQgJgDgIAAIgIABQgEABgEACQgFAFAAAHIAAAAIABAGQABADAEADQAEACAFADIAOAEQAMADAHADQAIADAGADQAFAEACAHQADAFAAAJQAAAKgEAHQgDAHgGAGQgHAFgIACQgJADgLAAIgMgBg");
	this.shape_17.setTransform(-100.8,10.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-192.4,0,385,23);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364.5,-45.5,729,91);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Transfer336x280();
	this.instance.setTransform(-59,24,0.884,0.884);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.setTransform(247.6,75.8,1,1,-90,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59,-92.2,316.6,336);


// stage content:
(lib.SCU201703_Transfer_728x90_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(693,6,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,2.167,0.321);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// ncua sidew
	this.instance = new lib.ncuahorizai();
	this.instance.setTransform(659,80,1.11,1.11,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border728x90();
	this.instance_1.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},180).wait(1));

	// PIC
	this.instance_2 = new lib.pic();
	this.instance_2.setTransform(122,30,0.851,0.851,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(80).to({x:-76.3},9).to({_off:true},1).wait(91));

	// HEAD
	this.instance_3 = new lib.HEAD1();
	this.instance_3.setTransform(564.5,35,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({x:368.5},9).wait(80).to({x:589.5},9).to({_off:true},2).wait(1));

	// CTA
	this.instance_4 = new lib.CTA();
	this.instance_4.setTransform(367.5,102,1,1,0,0,0,119.5,40);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(90).to({_off:false},0).wait(79).to({x:593.5},9).to({_off:true},2).wait(1));

	// shad
	this.instance_5 = new lib.HTML5rastershad_1();
	this.instance_5.setTransform(221,45,1,1,-90,0,0,0,10);
	this.instance_5.alpha = 0.199;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80).to({x:-24},9).wait(80).to({x:205},9).to({_off:true},2).wait(1));

	// tag
	this.instance_7 = new lib._2016TAG();
	this.instance_7.setTransform(612.3,76.4,1.037,1.037,0,0,0,0,2.7);

	this.instance_8 = new lib._2016TAG();
	this.instance_8.setTransform(612.3,77,1.037,1.037,0,0,0,0,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_7,p:{x:612.3}}]},81).to({state:[{t:this.instance_8},{t:this.instance_7,p:{x:105.5}}]},88).to({state:[]},11).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.setTransform(852.4,83,1.116,1.116,0,0,0,215.3,63.1);

	this.instance_10 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_10.setTransform(852.4,83.5,1.116,1.116,0,0,0,215.3,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_9,p:{x:852.4}}]},81).to({state:[{t:this.instance_10},{t:this.instance_9,p:{x:345.6}}]},88).to({state:[]},11).wait(1));

	// logo rule
	this.instance_11 = new lib._2016_SCU_logoruleai();
	this.instance_11.setTransform(706,64.5,1.154,1.154,0,0,0,81.4,0.5);

	this.instance_12 = new lib._2016_SCU_logoruleai();
	this.instance_12.setTransform(706,65,1.154,1.154,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_11,p:{x:706}}]},81).to({state:[{t:this.instance_12},{t:this.instance_11,p:{x:199.3}}]},88).to({state:[]},11).wait(1));

	// shad
	this.instance_13 = new lib.HTML5rastershad_1();
	this.instance_13.setTransform(700,92,1,1,-90,0,0,0,10);
	this.instance_13.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(80).to({y:98},0).to({x:508,y:79.1},9).to({_off:true},91).wait(1));

	// logo box
	this.instance_14 = new lib.box1();
	this.instance_14.setTransform(324.8,29.5,2.165,0.639,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({_off:true},180).wait(1));

	// ncua
	this.instance_15 = new lib.ncuahorizai();
	this.instance_15.setTransform(659,80,1.11,1.11,0,0,0,0,3.6);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// com
	this.instance_16 = new lib.comhoriz();
	this.instance_16.setTransform(661,82.7,0.687,0.687,0,0,0,0,4.5);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_17 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_17.setTransform(466.5,75,0.07,0.07,0,0,0,135,145);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(308.2,-52,848.9,357.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;