(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1490151595333", id:"HTML5rastershad"},
		{src:"images/Transfer336x280.jpg?1490151595333", id:"Transfer336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Transfer336x280 = function() {
	this.initialize(img.Transfer336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,166);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Transfer336x280();
	this.instance.setTransform(-17,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-17,0,336,166);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAPIAAgdIAdAAIAAAdg");
	this.shape.setTransform(115.1,44.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAJAHALAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEAEAAAFIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_1.setTransform(106,40.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMA9IgNgDQgLgFgJgJQgJgIgFgMIgDgLIgBgNIAAAAQAAgHAEgQQAFgLAJgJQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFAMQAFAPAAAIIAAAAIgBAMIgEAMQgFALgIAJQgJAJgMAFQgRAFgIAAgAgOgjQgHAEgFAFQgEAFgDAHQgDAHAAAHIAAAAQAAAHADAHQADAHAFAGQAFAFAHADQAGAEAHAAQAIAAAHgEQAGgDAFgFQAFgFADgHQACgHAAgIIAAAAQAAgGgDgHQgCgIgFgFQgFgFgHgEQgHgCgHAAQgHAAgHACg");
	this.shape_2.setTransform(92.9,40.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_3.setTransform(78.5,40.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZBRQgLgFgHgIQgJgIgFgLIgDgNIgBgOIAAgBQAAgKAEgPQAFgLAIgIQAIgIAKgFQAKgEALAAQAFAAAHACQAGACAFADQAJAFAHAKIAAhCIAdAAIAACmIgdAAIAAgUQgHALgJAFIgMAFQgFACgGAAQgKAAgKgEgAgMgNQgGADgFAFQgFAFgDAFQgCAIAAAIIAAABQAAAIACAIQAEAHAFAFQAEAFAGADQAHADAFAAQAGAAAHgDQAGgDAFgFQAFgFADgHQADgIAAgIIAAgBQAAgIgDgIQgDgFgFgFQgFgFgGgDQgGgDgHAAQgFAAgHADg");
	this.shape_4.setTransform(63.5,38.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMBTIAAh4IAaAAIAAB4gAgNg3IAAgbIAcAAIAAAbg");
	this.shape_5.setTransform(52.9,38.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLA9Igyh5IAeAAIAfBYIAhhYIAdAAIgyB5g");
	this.shape_6.setTransform(42.7,40.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABMQgHgCgEgEQgFgEgCgHQgDgHAAgKIAAg+IgPAAIAAgXIAPAAIAAgiIAaAAIAAAiIAgAAIAAAXIggAAIAAA6QAAAIAEADQADAEAIAAQAJAAAIgEIAAAXQgFADgGABQgHACgHAAQgIAAgEgCg");
	this.shape_7.setTransform(24.2,38.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgbA8QgIgDgGgEQgGgFgDgHQgEgHAAgJIAAgBQAAgKAEgHQAEgHAGgDQAHgFAJgDQAJgCALAAQAMAAATAFIAAgDQAAgFgCgFQgCgFgDgEQgEgDgGgCQgFgCgGAAQgJAAgJACIgQAGIgIgWQALgFAKgCQALgEAMAAQAOAAAKAEQAKADAGAHQAHAHADAKQAEAJAAAMIAABGIgcAAIAAgPQgHAIgJAFQgMAEgJAAQgJAAgIgCgAgKAGQgFABgEACQgDADgCADQgCAEAAAEIAAABQAAAIAHAFQAGAEALAAQAEAAAGgBQAGgCAEgEQAFgDACgFQADgFAAgFIAAgHQgRgEgLAAIgKABg");
	this.shape_8.setTransform(12.5,40.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFA9IgMgDQgLgFgJgJQgJgIgEgMQgFgMAAgMIAAAAQAAgMAFgLQAEgLAJgJQAJgJALgFIAMgEQAFgBAGAAQAIAAAIABQAHACAGADQAIAEAMALIgSATQgHgIgGgEQgIgEgKABQgGAAgGACQgGAEgFAFQgFAFgDAHQgCAHAAAHIAAAAQAAAHADAHQACAIAFAFQAFAFAHADQAFAEAHAAQAJAAAJgFQAHgDAHgIIARARQgNAMgIAFQgGADgHABQgIACgIAAg");
	this.shape_9.setTransform(-0.3,40.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeBMQgNgDgMgHIAKgVQAKAGALADQAKADAMAAQAHAAAIgCQAHgCAFgFQAEgFADgHQADgHAAgJIAAgJQgLAMgHAEQgFADgHABQgFACgGAAQgLAAgJgEQgLgEgHgHQgIgHgFgLQgEgJAAgNIAAAAQAAgJAEgPQAFgLAIgHQAIgHAKgEQAKgEAKAAQAGAAAGABQAGACAGADQAIAFAJAJIAAgSIAcAAIAABfQAAAPgFAMQgDALgIAIQgEAEgFADQgFADgHACQgSAEgJAAQgPAAgOgEgAgMg1QgGACgFAEQgFAFgDAGQgCAGAAAIIAAAAQAAAHACAHQADAGAFACQAFAFAGACQAGADAGAAQAGAAAHgDQAGgCAFgFQAGgCACgGQADgHAAgHIAAAAQAAgHgDgHQgCgGgGgEQgFgFgGgCQgHgDgGAAQgGAAgGADg");
	this.shape_10.setTransform(-21.9,42.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAaA+IAAhDQAAgIgBgFQgCgFgEgFQgDgDgFgCQgFgCgGAAQgEAAgFACQgFACgEAEQgDAEgCAGQgCAFAAAHIAABDIgcAAIAAh4IAcAAIAAATQAGgKAJgFQAEgDAGgBQAEgCAGAAQALgBAIAEQAIADAGAGQAFAHADAIQADAJAAAKIAABMg");
	this.shape_11.setTransform(-36.3,40.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNBTIAAh4IAbAAIAAB4gAgOg3IAAgbIAdAAIAAAbg");
	this.shape_12.setTransform(-46.8,38.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAaBUIAAhFQAAgIgBgFQgDgDgDgFQgDgDgFgCQgFgCgGAAQgEAAgFACQgFACgDAEQgEAEgCAEQgCAFAAAHIAABFIgcAAIAAimIAcAAIAABBQAGgKAJgFQAFgDAFgBQAEgCAGAAQALgBAIAEQAIADAGAGQAFAHADAIQADAJAAAIIAABOg");
	this.shape_13.setTransform(-57.1,38);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgFA9IgMgDQgLgFgJgJQgJgIgEgMQgFgMAAgMIAAAAQAAgMAFgLQAEgLAJgJQAJgJALgFIAMgEQAFgBAGAAQAIAAAIABQAHACAGADQAIAEAMALIgSATQgHgIgGgEQgIgEgKABQgGAAgGACQgGAEgFAFQgFAFgDAHQgCAHAAAHIAAAAQAAAHADAHQACAIAFAFQAFAFAHADQAFAEAHAAQAJAAAJgFQAHgDAHgIIARARQgNAMgIAFQgGADgHABQgIACgIAAg");
	this.shape_14.setTransform(-70.7,40.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAABMQgHgCgEgEQgFgEgCgHQgDgHAAgKIAAg+IgPAAIAAgXIAPAAIAAgiIAaAAIAAAiIAgAAIAAAXIggAAIAAA6QAAAIAEADQADAEAIAAQAJAAAIgEIAAAXQgFADgGABQgHACgHAAQgIAAgEgCg");
	this.shape_15.setTransform(-82.3,38.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgbA8QgIgDgGgEQgGgFgDgHQgEgHAAgJIAAgBQAAgKAEgHQAEgHAGgDQAHgFAJgDQAJgCALAAQAMAAATAFIAAgDQAAgFgCgFQgCgFgDgEQgEgDgGgCQgFgCgGAAQgJAAgJACIgQAGIgIgWQALgFAKgCQALgEAMAAQAOAAAKAEQAKADAGAHQAHAHADAKQAEAJAAAMIAABGIgcAAIAAgPQgHAIgJAFQgMAEgJAAQgJAAgIgCgAgKAGQgFABgEACQgDADgCADQgCAEAAAEIAAABQAAAIAHAFQAGAEALAAQAEAAAGgBQAGgCAEgEQAFgDACgFQADgFAAgFIAAgHQgRgEgLAAIgKABg");
	this.shape_16.setTransform(-93.9,40.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAaA9IgahRIgaBRIgZAAIgnh4IAcAAIAZBRIAbhSIAVAAIAbBSIAZhRIAcAAIgnB4g");
	this.shape_17.setTransform(-110.2,40.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_18.setTransform(127.8,13.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABAA+IAAhDQAAgIgCgGQgBgFgDgEQgDgEgFgBQgFgCgGAAQgFAAgFACQgFABgDAEQgEAFgCAFQgBAGAAAHIAABDIgaAAIAAhDQAAgIgCgGQgCgFgDgEQgDgEgFgBQgEgCgGAAQgGAAgEACQgFACgEAEQgDAEgCAGQgCAGAAAGIAABDIgcAAIAAh4IAcAAIAAASQAHgJAHgFIAKgFQAGgBAHAAQAHgBAFACQAGACAEACQAEADACAEIAGAJQAIgKAKgGQAFgCAGgCQAGgCAGABQAKAAAIACQAIAEAGAFQAFAHADAIQADAJAAALIAABMg");
	this.shape_19.setTransform(109.9,13.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgcA6QgIgDgFgGQgGgHgDgIQgDgJAAgKIAAhLIAcAAIAABCQAAAIACAFQACAGADAEQADADAFACQAFACAFAAQAFAAAFgCQAFgCAEgEQAEgDABgGQACgGAAgHIAAhCIAcAAIAAB3IgcAAIAAgTQgHAKgHAFIgLAFQgEABgHAAQgKABgIgEg");
	this.shape_20.setTransform(91.8,13.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAJAHALAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEAEAAAFIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_21.setTransform(78.8,13.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_22.setTransform(66.3,13.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAjBQIgmg4IgBAAIgjAAIAAA4IgcAAIAAifIBGAAQAKAAARAEQAMAEAHAIQAHAHAEAJQADAJAAAKIAAABQAAAJgDAIQgDAIgFAEQgFAGgHAFQgHAEgIACIArA9gAgnAAIAoAAQAHAAAHgBQAGgCAEgEQAFgDABgFQADgFAAgGIAAAAQAAgHgCgFQgCgFgFgDQgEgDgGgDQgGgBgIAAIgoAAg");
	this.shape_23.setTransform(51.7,11.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgOAPIAAgdIAdAAIAAAdg");
	this.shape_24.setTransform(32.8,17.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAJAHALAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEAEAAAFIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_25.setTransform(23.8,13.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgaBRQgKgFgIgIQgIgIgEgLIgEgNIgCgOIAAgBQABgKAFgPQAEgLAIgIQAIgIAKgFQAKgEALAAQAGAAAGACQAGACAFADQAJAFAHAKIAAhCIAcAAIAACmIgcAAIAAgUQgHALgJAFIgMAFQgFACgGAAQgLAAgKgEgAgLgNQgHADgFAFQgFAFgCAFQgDAIAAAIIAAABQAAAIADAIQACAHAGAFQAEAFAHADQAGADAFAAQAHAAAGgDQAHgDAEgFQAFgFADgHQADgIAAgIIAAgBQAAgIgDgIQgDgFgFgFQgEgFgHgDQgGgDgHAAQgGAAgFADg");
	this.shape_26.setTransform(10.2,11.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAaA+IAAhDQAAgIgBgFQgDgFgDgFQgDgDgFgCQgEgCgHAAQgEAAgFACQgFACgDAEQgEAEgCAGQgCAFAAAHIAABDIgcAAIAAh4IAcAAIAAATQAHgKAHgFQAGgDAFgCQAEgBAGAAQALgBAIAEQAIADAGAGQAFAHADAIQADAJAAAKIAABMg");
	this.shape_27.setTransform(-4.2,13.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgcA6QgIgDgGgGQgFgHgDgIQgDgJAAgKIAAhLIAcAAIAABCQAAAIABAFQADAGADAEQADADAFACQAFACAFAAQAFAAAFgCQAFgCAEgEQADgDACgGQACgGABgHIAAhCIAbAAIAAB3IgbAAIAAgTQgIAKgIAFIgKAFQgEABgGAAQgLABgIgEg");
	this.shape_28.setTransform(-18.6,13.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgVBUIAAhgIgPAAIAAgWIAPAAIAAgJQAAgKADgIQADgIAEgFQAFgFAGgCQAFgCAKAAQALAAALADIAAAXQgJgCgIAAQgHAAgFAEQgDAFAAAJIAAAHIAfAAIAAAWIgfAAIAABgg");
	this.shape_29.setTransform(-29.7,11);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQADgGADgGIAIgJQAFgFAHgCQAHgBAIAAIAAAdIgCAAQgJAAgIADQgHADgFAGQgEAGgDAJQgDAHAAAMIAAAvg");
	this.shape_30.setTransform(-45.3,13.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_31.setTransform(-57.5,13.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgVBUIAAhgIgPAAIAAgWIAPAAIAAgJQAAgKADgIQADgIAEgFQAFgFAGgCQAFgCAKAAQALAAALADIAAAXQgJgCgIAAQgHAAgEAEQgEAFgBAJIAAAHIAgAAIAAAWIgfAAIAABgg");
	this.shape_32.setTransform(-68.5,11);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAJAHALAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEAEAAAFIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_33.setTransform(-79,13.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAaA+IAAhDQAAgIgCgFQgCgFgCgFQgEgDgFgCQgEgCgHAAQgEAAgFACQgFACgDAEQgEAEgCAGQgCAFAAAHIAABDIgcAAIAAh4IAcAAIAAATQAHgKAHgFQAGgDAFgCQAEgBAHAAQAKgBAIAEQAIADAFAGQAGAHADAIQADAJAAAKIAABMg");
	this.shape_34.setTransform(-91.6,13.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgbA8QgIgDgGgEQgGgFgDgHQgEgHAAgJIAAgBQAAgKAEgHQAEgHAGgDQAHgFAJgDQAJgCALAAQAMAAATAFIAAgDQAAgFgCgFQgCgFgDgEQgEgDgGgCQgFgCgGAAQgJAAgJACIgQAGIgIgWQALgFAKgCQALgEAMAAQAOAAAKAEQAKADAGAHQAHAHADAKQAEAJAAAMIAABGIgcAAIAAgPQgHAIgJAFQgMAEgJAAQgJAAgIgCgAgKAFQgFACgEACQgDADgCADQgCAEAAAEIAAABQAAAIAHAFQAGAEALAAQAEAAAGgBQAGgCAEgEQAFgDACgFQADgFAAgFIAAgHQgRgEgLAAIgKAAg");
	this.shape_35.setTransform(-105.9,13.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQACgGAEgGIAIgJQAFgFAHgCQAHgBAIAAIAAAdIgCAAQgJAAgIADQgHADgGAGQgDAGgDAJQgDAHAAAMIAAAvg");
	this.shape_36.setTransform(-116.5,13.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgNBQIAAiFIgzAAIAAgaICBAAIAAAaIgzAAIAACFg");
	this.shape_37.setTransform(-129.2,11.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-1,298,54);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgbBGQgNgDgKgHIAJgTQAJAFAJAEQAKADALAAQAHAAAHgCQAGgDAEgEQAFgEACgHQADgGAAgJIAAgIQgKALgHAEQgEACgGABQgFACgGAAQgJAAgJgEQgKgDgHgGQgHgIgEgJQgEgIAAgLIAAgBQAAgJAEgNQAEgJAIgIQAHgGAJgEQAJgDAJAAQAGAAAFACQAGAAAFADQAIAFAHAJIAAgRIAaAAIAABXQAAAOgEAKQgDAKgHAHQgEAEgFACIgKAGQgRADgIAAQgOAAgMgDgAgLgxQgGADgEADQgFAEgCAGQgCAGAAAHIAAAAQAAAHACAFQACAGAFACQAEAFAGACQAGACAFAAQAGAAAGgCQAGgCAEgFQAFgCACgGQADgFAAgGIAAgBQAAgHgDgGQgCgFgFgFQgEgDgGgDQgGgCgGAAQgFAAgGACg");
	this.shape.setTransform(110.8,14.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_1.setTransform(97.6,13.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgLBMIAAhtIAXAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_2.setTransform(88,11.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AAWBMIgfgwIgQARIAAAfIgZAAIAAiXIAZAAIAABaIAsgwIAfAAIgsAsIAtBBg");
	this.shape_3.setTransform(79.6,11.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_4.setTransform(66.4,13.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgYA3QgIgCgFgFQgGgFgDgFQgDgIAAgIIAAAAQAAgJAEgHQADgGAGgDQAGgFAIgCQAIgCAKAAQAMAAARAFIAAgCQAAgHgCgEQgCgEgDgDIgJgFQgFgCgFABQgIAAgIABIgPAGIgHgVQAKgEAJgCQAKgDALAAQAMAAAJADQAJADAHAGQAGAHADAIQADAJAAALIAABAIgZAAIAAgOQgHAHgIAEQgLAFgIAAQgIAAgHgCgAgJAFQgFABgDADQgDABgCADQgCAEAAAEIAAAAQAAAIAHAFQAFADAKABQAEgBAFgBQAGgCAEgDQAEgDACgEQACgEAAgGIAAgGQgPgEgKgBQgEABgFABg");
	this.shape_5.setTransform(53.4,13.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("Ag8BJIAAiRIBAAAQANAAAJADQAKAEAHAGQAEAFADAGQACAGAAAHIAAABQAAAGgBAGQgCAEgDAFQgFAHgKAFIAMADQAGADADAEQAEAEACAGQADAGAAAIQAAAKgEAHQgEAIgHAEQgHAGgKACQgKADgNAAgAgiAyIAoAAIAMgBQAGgCADgCQAEgCACgEQACgEAAgFIAAAAQAAgFgCgEQgCgDgEgDQgEgDgFgBIgOgBIgmAAgAgigKIAiAAIAKgBQAFgCAEgCQAEgDACgDQACgEAAgFIAAAAQAAgEgCgEQgCgDgDgDQgDgDgFgBIgLgBIgjAAg");
	this.shape_6.setTransform(40.4,11.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgSA1QgKgEgIgIQgHgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAHgJAKgEIAKgDIAKgBIANABIAKADQAHADAKAKQAGAIAEALQADALAAAKIAAAHIhQAAQABAHADAFQADAGAEADQAEAEAGACQAFABAEAAQAJAAAIgDQAGgDAHgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQgBgHgCgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgFACgEADQgDAEgCAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_7.setTransform(19.8,13.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgLBMIAAiXIAXAAIAACXg");
	this.shape_8.setTransform(10.4,11.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgLBMIAAhtIAXAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_9.setTransform(4.4,11.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgFBLQgGgBgFgDQgIgEgGgJIAAARIgaAAIAAiYIAaAAIAAA9QAGgJAJgFQAFgDAFgBQAFgCAFAAQAKAAAJADQAKAFAHAHQAHAIAEAKQAFANAAAJIgBAOIgEALQgEAKgHAIQgHAIgKADQgJAFgKAAQgFAAgFgDgAgLgLQgGACgEAEQgFAFgCAFQgDAHAAAHQAAAIADAIQACAGAFAEQAEAFAGADQAGACAFAAQAGAAAGgCQAFgDAFgFQAEgEADgGQACgIAAgIQAAgHgDgHQgCgFgEgFQgFgEgFgCQgGgDgGAAQgFAAgGADg");
	this.shape_10.setTransform(-5.3,11.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgLA4IgLgDQgLgFgIgIQgIgIgEgKIgDgLIgBgLIAAAAQgBgGAFgPQAEgKAJgIQAHgIALgFIALgDIALgBQAIAAAPAEQALAEAIAIQAIAIAEALQAEAOABAHIgBALIgEALQgEAKgIAIQgJAIgKAFQgQAEgHAAgAgMgfQgHACgEAFQgEAFgDAGQgCAHAAAGQAAAHADAGQACAHAFAFQAEAFAGACQAHADAFAAQAHAAAHgDQAFgCAFgFQAEgFADgGQACgHAAgHIAAAAQAAgGgCgGQgDgHgFgFQgEgFgGgCQgHgDgGAAQgHAAgFADg");
	this.shape_11.setTransform(-19.5,13.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAuBJIAAhnIguBDIAAAAIgthDIAABnIgaAAIAAiRIAcAAIArBGIAshGIAcAAIAACRg");
	this.shape_12.setTransform(-35.5,11.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgXBJQgKgDgHgIQgHgIgFgKIgDgLIgBgOQAAgJAEgNQAEgKAIgIQAHgHAJgFQAJgDAKAAQAFAAAGACIAKADQAIAGAHAIIAAg8IAaAAIAACYIgaAAIAAgTQgHAKgIAFQgFADgFABQgGADgFAAQgJAAgJgFgAgLgLQgGACgEAEQgEAFgDAFQgCAHAAAHQAAAIACAIQADAGAEAEQAFAFAFADQAGACAFAAQAGAAAGgCQAGgDAEgFQAFgFACgFQADgIAAgIQAAgHgDgHQgCgFgFgFQgEgEgGgCQgGgDgGAAQgFAAgGADg");
	this.shape_13.setTransform(-58.2,11.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_14.setTransform(-71.4,13.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_15.setTransform(-84.5,13.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgLA4IgLgDQgLgFgIgIQgIgIgEgKIgDgLIgBgLIAAAAQgBgGAFgPQAEgKAJgIQAHgIALgFIALgDIALgBQAIAAAPAEQALAEAIAIQAIAIAEALQAEAOABAHIgBALIgEALQgEAKgIAIQgJAIgKAFQgQAEgHAAgAgMgfQgHACgEAFQgEAFgDAGQgCAHAAAGQAAAHADAGQACAHAFAFQAEAFAGACQAHADAFAAQAHAAAHgDQAFgCAFgFQAEgFADgGQACgHAAgHIAAAAQAAgGgCgGQgDgHgFgFQgEgFgGgCQgHgDgGAAQgHAAgFADg");
	this.shape_16.setTransform(-97.8,13.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgLBJQgIgBgIgDQgIgDgHgEQgHgFgGgGIAPgSQAHAGAPAJIALADIAMABIALgBIAIgEQADgCABgDQACgEABgFQAAgEgCgDQgBgDgEgCIgKgFIgOgFQgOgDgHgDQgKgEgGgDQgGgFgDgHQgDgHgBgKIAAAAQAAgKAEgIQAEgHAGgGQAIgGAJgDQAIgDALAAIAOABIANADQAKAEAPALIgOATQgKgIgKgDQgKgEgIAAIgKABQgFABgDADQgGAFAAAHIAAAAQAAAFABADQADADADADIAKAFIAQAFQAMADAIAEQAKADAFADQAHAFACAHQADAHAAAJQAAAKgEAJQgDAHgHAGQgIAGgJADQgJADgMAAQgHAAgIgCg");
	this.shape_17.setTransform(-111.5,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139,0,278,25);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A3WzcMAutAAAMAAAAm5MgutAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-125.5,301,251);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


// stage content:
(lib.SCU201703_Transfer_300x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(280,141,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,0.893,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.setTransform(150,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border300x250();
	this.instance_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A6PMRIAA4hMA0eAAAIAAYhg");
	var mask_graphics_80 = new cjs.Graphics().p("A6PMRIAA4hMA0eAAAIAAYhg");
	var mask_graphics_81 = new cjs.Graphics().p("A6PMVIAA4pMA0eAAAIAAYpg");
	var mask_graphics_82 = new cjs.Graphics().p("A6PMZIAA4xMA0eAAAIAAYxg");
	var mask_graphics_83 = new cjs.Graphics().p("A6PMeIAA47MA0eAAAIAAY7g");
	var mask_graphics_84 = new cjs.Graphics().p("A6PMiIAA5DMA0eAAAIAAZDg");
	var mask_graphics_85 = new cjs.Graphics().p("A6PMnIAA5NMA0eAAAIAAZNg");
	var mask_graphics_86 = new cjs.Graphics().p("A6PMrIAA5VMA0eAAAIAAZVg");
	var mask_graphics_87 = new cjs.Graphics().p("A6PMwIAA5fMA0eAAAIAAZfg");
	var mask_graphics_88 = new cjs.Graphics().p("A6PM0IAA5nMA0eAAAIAAZng");
	var mask_graphics_89 = new cjs.Graphics().p("A6PM4IAA5vMA0eAAAIAAZvg");
	var mask_graphics_169 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_170 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_171 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_172 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_173 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_174 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_175 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_176 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_177 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_178 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:168,y:62.5}).wait(80).to({graphics:mask_graphics_80,x:168,y:62.5}).wait(1).to({graphics:mask_graphics_81,x:168,y:59.2}).wait(1).to({graphics:mask_graphics_82,x:168,y:55.8}).wait(1).to({graphics:mask_graphics_83,x:168,y:52.5}).wait(1).to({graphics:mask_graphics_84,x:168,y:49.2}).wait(1).to({graphics:mask_graphics_85,x:168,y:45.8}).wait(1).to({graphics:mask_graphics_86,x:168,y:42.5}).wait(1).to({graphics:mask_graphics_87,x:168,y:39.2}).wait(1).to({graphics:mask_graphics_88,x:168,y:35.8}).wait(1).to({graphics:mask_graphics_89,x:168,y:32.5}).wait(80).to({graphics:mask_graphics_169,x:168,y:32}).wait(1).to({graphics:mask_graphics_170,x:168,y:19.3}).wait(1).to({graphics:mask_graphics_171,x:168,y:6.7}).wait(1).to({graphics:mask_graphics_172,x:168,y:-6}).wait(1).to({graphics:mask_graphics_173,x:168,y:-18.7}).wait(1).to({graphics:mask_graphics_174,x:168,y:-31.3}).wait(1).to({graphics:mask_graphics_175,x:168,y:-44}).wait(1).to({graphics:mask_graphics_176,x:168,y:-56.7}).wait(1).to({graphics:mask_graphics_177,x:168,y:-69.3}).wait(1).to({graphics:mask_graphics_178,x:168,y:-82}).wait(1).to({graphics:null,x:0,y:0}).wait(4));

	// PIC
	this.instance_2 = new lib.pic();
	this.instance_2.setTransform(132,57,1,1,0,0,0,150,57);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(169).to({regX:150.1,regY:57.1,x:132.1,y:57.1},0).to({y:-93.9},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_3 = new lib.HTML5rastershad_1();
	this.instance_3.setTransform(168,151,1,1,0,0,0,0,10);
	this.instance_3.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({y:125},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.setTransform(269.6,192,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:161},9).wait(80).to({y:49},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.setTransform(269.5,237,1,1,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).wait(79).to({y:130},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.setTransform(150,116.7,0.893,0.833,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(169).to({y:16.7},9).to({_off:true},4).wait(1));

	// tag
	this.instance_7 = new lib._2016TAG();
	this.instance_7.setTransform(150,218.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.setTransform(413.6,225.7,1.225,1.225,0,0,0,215.2,63);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.setTransform(253.3,205.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_10 = new lib.box1();
	this.instance_10.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},182).wait(1));

	// com
	this.instance_11 = new lib.comhoriz();
	this.instance_11.setTransform(67,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.setTransform(149.5,237.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,336,250);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;