(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 468,
	height: 60,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1489954661970", id:"HTML5rastershad"},
		{src:"images/YourPlace336x280.jpg?1489954661970", id:"YourPlace336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.YourPlace336x280 = function() {
	this.initialize(img.YourPlace336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgFAAgFgCgAAwAXQgFgFAAgGQAAgIAFgEQAGgCAJAAQAFAAAKACIAAgBQAAgNgPAAQgGAAgHAEIgDgGQAJgEAIAAQAKAAAGAFQAEAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgFgDgAAyALQAAAKAMAAQAGAAAFgEQAFgDAAgGIAAgEQgIgCgGAAQgOAAAAAJgAgjAUQgHgHAAgLQABgIAGgHQAGgHAKAAQAJAAAHAHQADAHAAAIIAAADIgjAAQABAHAFAEQAEAEAHAAQAIAAAGgGIAEAEQgHAIgLAAQgKAAgHgGgAgFAAQgBgOgNAAQgHAAgDAEQgFAEgBAGIAeAAIAAAAgAhfAUQgGgHAAgLQAAgJAGgHQAHgGAJAAQAKAAAIAKIAAgcIAHAAIAAA/IgHAAIAAgJQgHAKgLAAQgJAAgHgGgAhZgJQgFAFAAAGIAAAAQAAAIAFAFQAFAFAGAAQAHAAAFgFQAFgFAAgIIAAAAQAAgGgFgFQgFgFgHAAQgHAAgEAFgAiUAUQgHgHABgLQAAgIAFgHQAHgHAJAAQALAAAGAHQAGAHAAAIIgBADIglAAQACAPAOAAQAJAAAHgGIADAEQgHAIgMAAQgKAAgGgGgAh1AAQgCgOgOAAQgFAAgFAEQgDAEgCAGIAfAAIAAAAgAB7AZIAAg/IAHAAIAAA/gABjAZIAAg/IAIAAIAAA/gAAMAZIAAgsIAHAAIAAAMQAHgNAMAAIAAAHIAAAAQgIAAgFAGQgFAGgBAIIAAASgAi1AZIAAgmIgHAAIAAgGIAHAAIAAgEQAAgIADgEQAFgEAFAAIAIABIAAAGIgHgBQgHAAgBAKIAAAEIAPAAIAAAGIgPAAIAAAmg");
	this.shape.setTransform(-36.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA+AlIADgFQADABAEABQAGAAADgJIgUgsIAHAAIARAkIAPgkIAHAAIgTAtQgFANgLAAQgGAAgEgCgAE2AXQgGgFAAgHQAAgNAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAEAAAKIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAE3ALQAAAJAMAAQAGABAFgEQAEgDABgGIAAgFQgIgCgGAAQgOAAAAAKgAD7AIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgADNATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgIgHgGAAQgIABgEAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAAPAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAIgBAGAHQAIAHgBAIIAAABQABALgIAGQgGAHgIAAQgMAAgGgKgAATgJQgEAFAAAFIAAABQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgAhJATQgHgGAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgHgAhEgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAh+ATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAhgAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAjYAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAkNATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgACzAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAilAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgAkfAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAlXAZIAAgsIAHAAIAAAsgAlYgdIAAgIIAIAAIAAAIg");
	this.shape_1.setTransform(20.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSBRIAAggIAdAAIAAAggAgLAeIgFgjIABgBQALAAAGgCQAIgDAGgDQAFgDACgFQADgFAAgFIAAAAQAAgFgCgEQgCgEgDgDQgDgDgFgBQgFgCgGgBQgJABgKAEQgJAFgIAJIgRgTQAFgGAGgEIAMgIQAHgDAIgCQAIgCAHAAQAMAAAKADQAKAEAHAGQAHAFAEAJQAEAJAAALIAAAAQAAALgEAIQgDAIgHAFQgGAEgIADQgIAEgKABIgCATg");
	this.shape.setTransform(87.9,8.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAJAHALAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEAEAAAFIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_1.setTransform(76,10.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgiA9IAAh3IAcAAIAAAcQADgIADgFIAIgKQAFgDAHgCQAHgCAIgBIAAAeIgCAAQgJAAgIADQgHADgFAGQgEAGgDAJQgDAIAAALIAAAug");
	this.shape_2.setTransform(66.3,10.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcA6QgIgDgGgGQgFgGgDgJQgDgIAAgLIAAhMIAcAAIAABEQAAAGABAGQADAFADAEQADAFAFABQAFACAFAAQAFAAAFgCQAFgCADgEQAFgDABgGQADgGgBgHIAAhDIAcAAIAAB4IgcAAIAAgTQgGAKgIAFIgLAFQgEABgHAAQgKAAgIgDg");
	this.shape_3.setTransform(53.8,10.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgJQgJgIgFgLIgDgNIgBgMIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFAQAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAHQADAGAFAGQAFAGAHACQAGADAHAAQAIAAAHgDQAGgCAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_4.setTransform(39.2,10.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgiA9IAAh3IAcAAIAAAcQACgIAEgFIAIgKQAGgDAGgCQAHgCAIgBIAAAeIgCAAQgJAAgIADQgHADgFAGQgEAGgDAJQgDAIAAALIAAAug");
	this.shape_5.setTransform(20.6,10.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgJQgJgIgFgLIgDgNIgBgMIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFAQAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAHQADAGAFAGQAFAGAHACQAGADAHAAQAIAAAHgDQAGgCAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_6.setTransform(7.7,10.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgLIgDgNIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADALQAEAMAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgHIARAOIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgEgFgCQgGgDgGAAQgFAAgFACQgFACgFAEQgEAFgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_7.setTransform(-13.6,10.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFA+IgMgEQgLgFgJgJQgJgIgEgLQgFgNAAgMIAAAAQAAgLAFgMQAEgMAJgIQAJgJALgFIAMgEQAFgBAGAAQAIAAAIABQAHACAGADQAIADAMAMIgSASQgHgHgGgEQgIgDgKAAQgGAAgGACQgGADgFAGQgFAFgDAHQgCAHAAAHIAAAAQAAAIADAHQACAHAFAFQAFAGAHACQAFADAHAAQAJAAAJgDQAHgEAHgHIARAQQgNANgIADQgGAEgHABQgIACgIAAg");
	this.shape_8.setTransform(-27,10.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA8QgIgCgGgFQgGgFgDgHQgEgHAAgJIAAAAQAAgKAEgIQAEgHAGgEQAHgFAJgCQAJgCALAAQAMAAATAFIAAgCQAAgHgCgFQgCgFgDgDQgEgDgGgCQgFgBgGAAQgJAAgJABIgQAGIgIgWQALgFAKgDQALgDAMAAQAOABAKADQAKAEAGAGQAHAHADAJQAEAKAAAMIAABGIgcAAIAAgPQgHAIgJAEQgMAGgJgBQgJAAgIgCgAgKAGQgFABgEACQgDADgCAEQgCADAAAEIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAEgDQAFgEACgEQADgFAAgGIAAgHQgRgFgLABIgKABg");
	this.shape_9.setTransform(-40.8,10.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgMBTIAAilIAZAAIAAClg");
	this.shape_10.setTransform(-50.4,8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag9BQIAAidIAcAAIAAAVQAHgLAJgFQAFgEAGgBQAGgCAGAAQALAAAKAEQAKAEAIAJQAIAIAEALQAFARAAAKIAAAAIgBAPIgEALQgEALgIAIQgIAIgKAFQgKAEgLgBQgGAAgGgBIgLgFQgJgFgHgKIAAA4gAgMg0QgHADgEAFQgGAFgCAHQgDAHAAAJIAAAAQAAAJADAHQACAFAGAGQAEAFAHACQAGADAGAAQAGAAAHgDQAGgCAFgFQAFgGACgFQADgHAAgJIAAAAQAAgJgDgHQgCgHgFgFQgFgFgGgDQgHgDgGAAQgGAAgGADg");
	this.shape_11.setTransform(-61.1,12.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgiA9IAAh3IAcAAIAAAcQACgIAEgFIAIgKQAGgDAGgCQAHgCAIgBIAAAeIgCAAQgJAAgHADQgIADgGAGQgDAGgDAJQgDAIAAALIAAAug");
	this.shape_12.setTransform(-80.2,10.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcA6QgIgDgGgGQgFgGgDgJQgDgIAAgLIAAhMIAcAAIAABEQAAAGABAGQACAFAEAEQADAFAFABQAFACAFAAQAFAAAFgCQAFgCADgEQAEgDACgGQACgGAAgHIAAhDIAcAAIAAB4IgcAAIAAgTQgHAKgIAFIgKAFQgEABgGAAQgLAAgIgDg");
	this.shape_13.setTransform(-92.7,10.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgJQgJgIgFgLIgDgNIgBgMIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFAQAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAHQADAGAFAGQAFAGAHACQAGADAHAAQAIAAAHgDQAGgCAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_14.setTransform(-107.3,10.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgNBQIAAg/IhAhgIAiAAIArBIIAthIIAhAAIhABfIAABAg");
	this.shape_15.setTransform(-121.1,8.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-177,-4,319,27);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("A8lFJIAAqSMA5LAAAIAAKSg");
	this.shape.setTransform(238,33,1.3,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,476,66);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgLAeQgJgEgEgDIAHgKQAFAEAFACQAGACACAAQAFAAADgCQACgCAAgDIAAAAQAAgDgEgDIgIgDQgKgDgDgCIgFgEQgCgDAAgFQAAgEACgEQACgDADgDQADgDAEgBQAEgBADAAQAGAAAGACQAGACAFADIgGAKIgJgEIgIgCQgDAAgCACQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAABQAAADAEACIAIAEIAHACIAGACIAFAFQACADAAAEIAAABQAAAEgCAEQgCAEgDADIgIADIgJABQgFAAgHgCg");
	this.shape.setTransform(146.3,10.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgJAeQgGgCgFgEQgEgFgDgGIgBgGIgBgHQAAgFACgGQACgHAFgEQAEgEAFgDIAGgCIAFgBIAHABIAGACIAKAIQADAEACAHQACAGAAAEIAAAFIgtAAQABADACADIAEAFIAFADIAFABQAFAAAEgCQAEgBAEgEIAIAHIgFAGIgFADIgHADIgJABQgEgBgGgCgAAQgDIgCgGIgDgGIgFgDQgDgCgDAAQgCAAgCACQgDABgCACIgEAFIgCAHIAfAAIAAAAg");
	this.shape_1.setTransform(139.8,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAOArIAAgkIgBgGIgDgDIgEgDIgGgBIgEABIgFADIgCADIgBAHIAAAjIgPAAIAAhVIAPAAIAAAiQADgFAFgDIAEgCIAGgBQAFAAAEABQAEACADADQADADABAFQACAEAAAEIAAAog");
	this.shape_2.setTransform(132.5,9.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgCAgIgGgCQgGgCgFgFQgEgEgDgGQgCgGAAgHQAAgFACgGQADgHAEgEQAFgEAGgDIAGgCIAFgBIAIABIAHADQAEABAHAHIgJAJQgFgEgDgCQgEgCgFAAQgDAAgCACIgGAEIgEAGQgBAEAAADIAAAAIABAIIAEAGIAGAEQACACAEAAQAEAAAFgDQAEgBADgEIAJAIQgGAHgFACQgDACgDABIgJABg");
	this.shape_3.setTransform(125.4,10.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AANAgIAAgiIgBgHIgCgFIgEgDIgGgBIgEABIgEADIgEAFIgBAHIAAAiIgOAAIAAg+IAOAAIAAAKQAEgFAEgDIAFgCIAGgBQAFAAAEACQAEABADAEQADADACAEQABAFAAAFIAAAng");
	this.shape_4.setTransform(118.3,10.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AgNAfQgFgBgDgDIgFgGQgBgEAAgEIAAAAQAAgGABgDQACgEAEgBIAIgEQAFgBAFgBQAGAAAKAEIAAgCIgBgFIgDgFIgFgCIgFgBIgJABIgJACIgEgLIALgEQAGgCAFAAQAHABAFACQAGABADADQAEAEABAFQACAFAAAGIAAAkIgOAAIAAgIQgEAFgFABQgFAEgFAAQgEgBgEgBgAgFACIgEADIgDADIgBAEQAAAEADADQAEADAFAAIAFgCIAFgDQADgBABgCIABgGIAAgDQgJgDgFAAIgFAAg");
	this.shape_5.setTransform(110.9,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AgRAgIAAg+IAPAAIAAAPIACgHIAEgFIAGgDIAIgBIAAAQIgBAAQgFAAgEABQgEACgDADQgBADAAAFQgCACAAAHIAAAYg");
	this.shape_6.setTransform(105.3,10.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AghApIAAhRIAjAAQAHAAAGACQAGACADADIAEAGQACADAAAFIgBAHIgDAFQgDAEgFADIAHABIAFAEQACACABAEIABAHIAAABQAAAFgCAFQgCADgEADQgEAEgGABQgGACgHgBgAgTAdIAXAAIAGgBIAFgDIAEgDIABgFIAAgBIgBgEIgEgEIgFgCIgIgBIgVAAgAgTgFIATAAIAGgBIAFgCIADgEQABgBAAgEIgBgEIgDgDIgEgDIgHgBIgTAAg");
	this.shape_7.setTransform(98.5,9.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgJAeQgGgCgFgEQgEgFgDgGIgBgGIgBgHQAAgFACgGQACgHAFgEQAEgEAFgDIAGgCIAFgBIAHABIAGACIAKAIQADAEACAHQACAGAAAEIAAAFIgtAAQABADACADIAEAFIAFADIAFABQAFAAAEgCQAEgBAEgEIAIAHIgFAGIgFADIgHADIgJABQgEgBgGgCgAAQgDIgCgGIgDgGIgFgDQgDgCgDAAQgCAAgCACQgDABgCACIgEAFIgCAHIAfAAIAAAAg");
	this.shape_8.setTransform(86.7,10.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgCAgIgGgCQgGgCgEgFQgFgEgDgGQgCgGAAgHQAAgFACgGQADgHAFgEQAEgEAGgDIAGgCIAFgBIAIABIAHADQAEABAGAHIgJAJQgEgEgDgCQgEgCgFAAQgDAAgCACIgGAEIgEAGQgCAEAAADIAAAAIACAIIAEAGIAGAEQACACAEAAQAEAAAFgDQAEgBADgEIAJAIQgHAHgEACQgDACgEABIgIABg");
	this.shape_9.setTransform(79.8,10.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgGArIAAg9IANAAIAAA9gAgGgcIAAgOIANAAIAAAOg");
	this.shape_10.setTransform(74.6,9.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AgFAgIgag+IAPAAIAQAsIARgsIAPAAIgaA+g");
	this.shape_11.setTransform(69.3,10.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AgRAgIAAg+IAPAAIAAAPIACgHIAEgFIAGgDIAIgBIAAAQIgBAAQgFAAgEABQgDACgEADQgBADAAAFQgCACAAAHIAAAYg");
	this.shape_12.setTransform(63.6,10.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgJAeQgGgCgFgEQgEgFgDgGIgBgGIgBgHQAAgFACgGQACgHAFgEQAEgEAFgDIAGgCIAFgBIAHABIAGACIAKAIQADAEACAHQACAGAAAEIAAAFIgtAAQABADACADIAEAFIAFADIAFABQAFAAAEgCQAEgBAEgEIAIAHIgFAGIgFADIgHADIgJABQgEgBgGgCgAAQgDIgCgGIgDgGIgFgDQgDgCgDAAQgCAAgCACQgDABgCACIgEAFIgCAHIAfAAIAAAAg");
	this.shape_13.setTransform(57.2,10.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AgGAqIgJgCIgIgFIgIgFIAJgLIAMAIIAHACIAGABIAGgBIAFgDIACgDIABgEIgBgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAIgGgEIgIgCIgLgDQgGgDgDgBQgEgDgCgDQgBgFgBgFIAAgBQABgFABgEQADgFAEgDIAJgFQAFgBAFAAIAIAAIAIACQAFACAJAGIgIALIgMgHQgGgCgEAAIgFABIgEACQgEADABAEIAAAFIADADIAHADIAHADIAMADQAFACADACQAEACACAEQABAEAAAFQAAAHgCAEQgCAFgEADQgEADgFACQgGACgHgBIgIAAg");
	this.shape_14.setTransform(49.7,9.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgQAHIAAgNIAhAAIAAANg");
	this.shape_15.setTransform(43.5,9.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgGArIAAhVIANAAIAABVg");
	this.shape_16.setTransform(39.4,9.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AgGArIAAhVIANAAIAABVg");
	this.shape_17.setTransform(36,9.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgOAeQgFgCgCgDQgDgDgCgEQgBgFAAgFIAAgnIAOAAIAAAiIACAHQAAACACACIAEAEIAFABIAFgBIAEgEIADgEIABgHIAAgiIAPAAIAAA9IgPAAIAAgKQgDAGgEADIgGACIgFABQgFAAgEgCg");
	this.shape_18.setTransform(30.6,10.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgeApIAAhRIA9AAIAAANIguAAIAAAXIAoAAIAAALIgoAAIAAAig");
	this.shape_19.setTransform(23.3,9.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AAJAqIAAgTIgoAAIgDgLIAtg1IAMAAIAAA0IAMAAIAAAMIgMAAIAAATgAgQALIAZAAIAAgfg");
	this.shape_20.setTransform(11.3,9.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AgdAqIAAgMIAdgYIAKgLIADgEIABgGIgBgGIgDgDQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAIgGgBIgDABIgFACQgEADgFAHIgLgJIAGgHIAHgFQAEgDAEgBIAIgBQAGAAAGABQAFACADAEQAEADACAFQACAEAAAGIgBAJIgEAHIgHAHIgKAIIgPAOIAmAAIAAANg");
	this.shape_21.setTransform(3.6,9.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgGAdIAAgXIgWAAIAAgLIAWAAIAAgXIAMAAIAAAXIAYAAIAAALIgYAAIAAAXg");
	this.shape_22.setTransform(-7.4,9.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AgPAoQgHgDgGgDIAFgLQAFADAGACQAFABAHAAIAGgBIAHgDQACgCABgFQACgDAAgFIAAgEQgGAGgDACIgGACIgGABQgFAAgFgCQgGgCgEgEQgEgEgCgFQgCgEAAgGIAAgBQAAgEACgJQACgFAFgEQAEgDAFgCQAFgCAFgBIAGABIAGADQAEACAFAFIAAgJIAOAAIAAAwQAAAIgCAGQgCAGgEAEIgFADIgGAEIgNACQgIAAgHgCgAgGgbQgDABgDACIgDAGQgCADAAAEQAAAEACAEIAEADIAFAEIAGABIAGgBIAGgEIAEgDIACgHIAAgBIgCgHIgEgGQgCgCgEgBQgDgCgDABQgDgBgDACg");
	this.shape_23.setTransform(-19,11.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AAOAgIAAgiIgCgHIgCgFIgEgDIgGgBIgEABIgEADIgDAFIgCAHIAAAiIgOAAIAAg+IAOAAIAAAKQAEgFAEgDIAFgCIAGgBQAFAAAEACQAEABADAEQADADABAEQACAFAAAFIAAAng");
	this.shape_24.setTransform(-26.5,10.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgGArIAAg9IANAAIAAA9gAgGgcIAAgOIANAAIAAAOg");
	this.shape_25.setTransform(-32,9.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAMArIgRgbIgJAJIAAASIgOAAIAAhVIAOAAIAAAyIAZgaIARAAIgZAYIAaAlg");
	this.shape_26.setTransform(-36.8,9.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AANAgIAAgiIgBgHIgCgFIgFgDIgFgBIgEABIgEADIgEAFIgBAHIAAAiIgOAAIAAg+IAOAAIAAAKQAEgFAEgDIAFgCIAFgBQAGAAAEACQAEABADAEQADADACAEQABAFAAAFIAAAng");
	this.shape_27.setTransform(-44.3,10.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgNAfQgFgBgDgDIgFgGQgBgEAAgEIAAAAQAAgGABgDQACgEAEgBIAIgEQAFgBAFgBQAGAAAKAEIAAgCIgBgFIgDgFIgFgCIgFgBIgJABIgJACIgEgLIALgEQAGgCAFAAQAHABAFACQAGABADADQAEAEABAFQACAFAAAGIAAAkIgOAAIAAgIQgEAFgFABQgFAEgFAAQgEgBgEgBgAgFACIgEADIgDADIgBAEQAAAEADADQAEADAFAAIAFgCIAFgDQADgBABgCIABgGIAAgDQgJgDgFAAIgFAAg");
	this.shape_28.setTransform(-51.7,10.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AghApIAAhRIAjAAQAHAAAGACQAGACADADIAEAGQACADAAAFIgBAHIgDAFQgDAEgFADIAHABIAFAEQACACABAEIABAHIAAABQAAAFgCAFQgCADgEADQgEAEgGABQgGACgHgBgAgTAdIAXAAIAGgBIAFgDIAEgDIABgFIAAgBIgBgEIgEgEIgFgCIgIgBIgVAAgAgTgFIATAAIAGgBIAFgCIADgEQABgBAAgEIgBgEIgDgDIgEgDIgHgBIgTAAg");
	this.shape_29.setTransform(-59.1,9.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgJAeQgGgCgFgEQgEgFgDgGIgBgGIgBgHQAAgFACgGQACgHAFgEQAEgEAFgDIAGgCIAFgBIAHABIAGACIAKAIQADAEACAHQACAGAAAEIAAAFIgtAAQABADACADIAEAFIAFADIAFABQAFAAAEgCQAEgBAEgEIAIAHIgFAGIgFADIgHADIgJABQgEgBgGgCgAAQgDIgCgGIgDgGIgFgDQgDgCgDAAQgCAAgCACQgDABgCACIgEAFIgCAHIAfAAIAAAAg");
	this.shape_30.setTransform(-70.9,10.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgGArIAAhVIANAAIAABVg");
	this.shape_31.setTransform(-76.2,9.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#002663").s().p("AgGArIAAg9IANAAIAAA9gAgGgcIAAgOIANAAIAAAOg");
	this.shape_32.setTransform(-79.6,9.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#002663").s().p("AgCArIgGgCQgFgEgEgFIAAAKIgOAAIAAhVIAOAAIAAAiQAEgFAFgDQADgBADgBIAFgBQAGAAAFACQAFACAEAFQAFAEACAFQACAHAAAGIAAAAIAAAHIgCAHQgCAGgFAEQgEAEgFACQgFADgGAAIgFgBgAgGgGIgFAEQgDACgBADIgCAIIAAAAQAAAEACAFQABADADACIAFAFIAGABIAHgBIAFgFIAEgFQACgFAAgEIAAAAQAAgFgCgDQgBgDgDgCIgFgEIgHgCQgCAAgEACg");
	this.shape_33.setTransform(-85.1,9.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#002663").s().p("AgGAgIgGgCQgGgCgFgFQgEgEgDgGIgBgGIgBgHQAAgDACgIQADgHAFgEQAEgEAGgDIAHgCIAFgBQAFAAAIADQAGADAFAEQAEAEADAHQACAHAAAEIAAAAIAAAGIgCAGQgDAGgEAFQgFAFgGACQgJACgEABgAgGgRQgEABgCADIgEAGQgCAEAAADIAAAAIACAIIAEAGIAGAEQAEACACAAQAEAAAEgCIAGgEIAEgGIABgIIgCgHQgBgDgCgDQgDgDgEgBQgDgCgEAAQgDAAgDACg");
	this.shape_34.setTransform(-93.2,10.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#002663").s().p("AAaApIAAg6IgaAmIAAAAIgZgmIAAA6IgPAAIAAhRIAQAAIAYAnIAZgnIAQAAIAABRg");
	this.shape_35.setTransform(-102.3,9.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#002663").s().p("AgNApQgFgCgEgEQgFgEgCgGIgCgHIAAgHIAAAAQAAgGACgHQACgFAFgEQAEgFAFgCQAFgCAGAAIAFABIAGACQAFADAEAFIAAgiIAOAAIAABVIgOAAIAAgKQgEAGgFADIgGACIgFABQgGAAgFgDgAgGgGQgDABgCADIgEAEQgCAEAAAFIAAAAQAAAEACAFIAEAFQACADAEACIAFABQADAAADgBQAEgCACgDQADgCABgEQACgEAAgEIAAAAQAAgFgCgDQgBgDgDgCIgGgEQgDgCgDAAIgGACg");
	this.shape_36.setTransform(-115.3,9.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#002663").s().p("AANAgIAAgiIgBgHIgCgFIgFgDIgFgBIgEABIgFADIgDAFIgBAHIAAAiIgOAAIAAg+IAOAAIAAAKQAEgFAFgDIAEgCIAFgBQAGAAAEACQAEABADAEQADADACAEQABAFAAAFIAAAng");
	this.shape_37.setTransform(-122.8,10.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#002663").s().p("AgOAeQgFgCgCgDQgDgDgBgEQgCgFAAgFIAAgnIAOAAIAAAiIABAHQABACACACIAEAEIAFABIAEgBIAGgEIACgEIABgHIAAgiIAPAAIAAA9IgPAAIAAgKQgDAGgFADIgFACIgFABQgFAAgEgCg");
	this.shape_38.setTransform(-130.2,10.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#002663").s().p("AgGAgIgGgCQgGgCgFgFQgEgEgDgGIgBgGIgBgHQAAgDACgIQADgHAFgEQAEgEAGgDIAHgCIAFgBQAFAAAIADQAGADAFAEQAEAEADAHQACAHAAAEIAAAAIAAAGIgCAGQgDAGgEAFQgFAFgGACQgJACgEABgAgGgRQgEABgCADIgEAGQgCAEAAADIAAAAIACAIIAEAGIAGAEQAEACACAAQAEAAAEgCIAGgEIAEgGIABgIIgCgHQgBgDgCgDQgDgDgEgBQgDgCgEAAQgDAAgDACg");
	this.shape_39.setTransform(-137.9,10.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#002663").s().p("AgGAqIgJgCIgIgFIgIgFIAJgLIANAIIAGACIAFABIAHgBIAFgDIACgDIABgEIgBgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAIgGgEIgIgCIgLgDQgGgDgDgBQgEgDgCgDQgBgFAAgFIAAgBQAAgFABgEQACgFAFgDIAJgFQAFgBAFAAIAIAAIAIACQAFACAIAGIgHALIgMgHQgFgCgFAAIgFABIgEACQgDADAAAEIAAAFIADADIAHADIAHADIAMADQAFACADACQAEACACAEQABAEAAAFQAAAHgCAEQgCAFgEADQgEADgFACQgGACgHgBIgIAAg");
	this.shape_40.setTransform(-145.7,9.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159.5,2,319,16);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border468x60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgkegEmMBI9AAAIAAJNMhI9AAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-234.5,-30.5,469,61);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.YourPlace336x280();
	this.instance.setTransform(87,21,0.447,0.447);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.setTransform(247.6,75.8,1,1,-90,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(87,-92.2,170.6,336);


// stage content:
(lib.SCU201703_YourPlace_468x60_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(450,5,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,1.393,0.214);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.setTransform(385,53.9,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.setTransform(236,51.2,1.11,1.11,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border468x60();
	this.instance_2.setTransform(234,30);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},180).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.setTransform(51.7,30,0.851,0.851,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({x:-76.3},9).to({_off:true},1).wait(91));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.setTransform(425.5,34,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({x:296.5},9).wait(80).to({x:442.5},9).to({_off:true},2).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.setTransform(280.5,67,1,1,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).wait(79).to({x:426.6},9).to({_off:true},2).wait(1));

	// shad
	this.instance_6 = new lib.HTML5rastershad_1();
	this.instance_6.setTransform(155,45,1,1,-90,0,0,0,10);
	this.instance_6.alpha = 0.199;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.setTransform(181.5,124.8,0.872,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80).to({regX:167.9,scaleX:0.68,x:112.6},9).wait(80).to({x:258.6},9).to({_off:true},2).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.setTransform(71.7,51,0.716,0.716,0,0,0,0,2.6);

	this.instance_9 = new lib._2016TAG();
	this.instance_9.setTransform(394.1,51.2,0.716,0.716,0,0,0,0,2.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_9},{t:this.instance_8}]},81).to({state:[]},99).wait(1));

	// logo
	this.instance_10 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_10.setTransform(237.4,55.6,0.771,0.771,0,0,0,215.2,63.1);

	this.instance_11 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_11.setTransform(559.8,55.8,0.771,0.771,0,0,0,215.2,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_11},{t:this.instance_10}]},81).to({state:[]},99).wait(1));

	// logo rule
	this.instance_12 = new lib._2016_SCU_logoruleai();
	this.instance_12.setTransform(136.4,42.8,0.797,0.797,0,0,0,81.4,0.5);

	this.instance_13 = new lib._2016_SCU_logoruleai();
	this.instance_13.setTransform(458.8,43,0.797,0.797,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_13},{t:this.instance_12}]},81).to({state:[]},99).wait(1));

	// shad
	this.instance_14 = new lib.HTML5rastershad_1();
	this.instance_14.setTransform(460.2,71,1,1,-90,0,0,0,10);
	this.instance_14.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(80).to({x:331},9).to({_off:true},91).wait(1));

	// logo box
	this.instance_15 = new lib.box1();
	this.instance_15.setTransform(209,19.8,1.393,0.429,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},180).wait(1));

	// EHO
	this.instance_16 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_16.setTransform(164.5,46.2,0.07,0.07,0,0,0,135,145);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(232.1,-67,472.1,336.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;