(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1490074702711", id:"HTML5rastershad"},
		{src:"images/Teensy336x280.jpg?1490074702711", id:"Teensy336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Teensy336x280 = function() {
	this.initialize(img.Teensy336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Teensy336x280();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAVIAAgpIAnAAIAAApg");
	this.shape.setTransform(153,55.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbBOQgPgFgLgMQgMgLgGgQIgFgQIgCgSIAAAAQAAgRAGgPQAGgQALgLQALgMAOgGIAPgGIAPgBQAKAAAJABIAQAGQAJAFAPAOQAKAMAFAQQAFAQAAAQIgBAKIh2AAQABAKAEAIQAFAIAGAFQAGAGAIACQAIADAHAAQANAAALgFQAKgFAKgKIAWAUQgGAHgHAGQgHAFgIAEQgIAEgKADQgKACgLAAQgPAAgQgHgAAqgKQgBgKgEgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgGAAgIAEQgHADgGAGQgFAFgEAIQgDAIgBAKIBSAAIAAAAg");
	this.shape_1.setTransform(139.5,49.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgRBxIAAjhIAkAAIAADhg");
	this.shape_2.setTransform(125.7,46.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglBRQgKgDgIgHQgJgGgEgKQgFgJAAgMIAAgBQAAgNAFgLQAFgJAJgFQAJgHAMgDQAMgEAOAAQASAAAaAHIAAgDQAAgIgDgHQgCgGgGgFQgFgEgHgDQgIgCgIAAQgMAAgMADQgKACgMAFIgLgeQAQgGAMgEQAQgDARAAQASAAANAEQAOAFAJAJQAJAJAEANQAFAMAAARIAABfIgmAAIAAgUQgJAKgMAGQgRAHgNAAQgLAAgLgDgAgOAHQgHACgFADQgFAEgCAFQgDAEAAAGIAAABQAAALAJAHQAJAGAOAAQAHAAAIgCQAIgDAGgFQAGgEADgHQADgGAAgHIAAgKQgXgGgOAAQgHAAgHABg");
	this.shape_3.setTransform(111.8,49.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeBOQgYgKgJgIIAQgaQANAKAOAFQAOAGALAAQALAAAIgFQAGgFAAgIIAAgBQAAgIgLgGQgGgDgRgGQgZgHgKgGQgIgFgEgIQgEgIAAgMIAAAAQAAgMAEgJQAEgJAJgHQAHgGALgEQALgDAJAAQAPAAARAFQAPAFANAIIgOAbQgNgHgLgEQgNgEgJAAQgJAAgHAEQgFAFAAAHIAAABQAAAHALAGIAYAKIASAGQAKAEAGADQAIAGAEAHQAFAJgBAKIAAABQABANgFAKQgFAJgIAHQgJAGgLADQgKADgNAAQgQAAgSgGg");
	this.shape_4.setTransform(95.2,49.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAjBTIAAhbQAAgKgCgHQgCgIgFgEQgEgFgHgEQgGgCgIAAQgHAAgGADQgHACgFAGQgFAFgDAHQgDAJAAAIIAABbIglAAIAAiiIAlAAIAAAaQAKgNALgIQAGgEAHgCQAGgCAJAAQAOAAAMAFQAKAEAIAIQAHAJAEALQAEALAAAPIAABmg");
	this.shape_5.setTransform(68.8,49.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgRBTIgQgFQgQgHgMgLQgMgMgGgPIgFgQIgCgRIAAAAQAAgKAHgVQAGgQAMgMQAMgMAQgGIARgGIAQgBQAMAAAXAHQAPAGAMAMQAMALAGAQQAHAVAAALIAAAAIgCAQIgFAQQgGAPgMAMQgMAMgQAHQgWAHgMAAgAgTgvQgJAEgHAHQgGAIgEAIQgDAKAAAKIAAAAQAAAKAEAKQADAJAHAIQAHAHAJAEQAJAEAJAAQALAAAJgEQAJgEAHgHQAGgIAEgJQADgJAAgLIAAAAQAAgJgDgKQgEgJgHgIQgHgHgJgEQgJgFgKABQgKgBgJAFg");
	this.shape_6.setTransform(48.9,49.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBBnQgJgDgGgFQgGgGgDgJQgEgKAAgNIAAhUIgVAAIAAggIAVAAIAAgtIAkAAIAAAtIAsAAIAAAgIgsAAIAABOQAAALAFAFQAFAFAKAAQAMAAALgGIAAAfQgHAEgIACQgJACgKAAQgLAAgGgCg");
	this.shape_7.setTransform(22.9,47.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgRBwIAAiiIAkAAIAACigAgThLIAAgkIAnAAIAAAkg");
	this.shape_8.setTransform(12.3,46.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJBwQgIgCgHgFQgMgHgKgMIAAAZIglAAIAAjhIAlAAIAABaQAKgOANgHQAHgFAIgCQAIgCAIAAQAOAAAOAGQAOAFAKALQAMALAGAPQAGAVAAAOIAAABIgCATIgEARQgGAPgLALQgLALgOAFQgNAHgPgBQgIAAgJgCgAgRgSQgJAEgGAHQgHAHgEAHQgEALAAALIAAABQAAALAEAKQAEAJAHAIQAGAGAJAEQAJAEAIAAQAJAAAIgEQAJgEAGgGQAHgIADgJQAEgKAAgLIAAgBQAAgLgEgLQgDgHgHgHQgGgHgJgEQgIgEgJABQgIgBgJAEg");
	this.shape_9.setTransform(-2,46.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2BoQgJgDgJgFIAMgbQAMAGALAAQAHAAAGgEQAFgFAFgKIhEiiIAnAAIAtB4IAqh4IAnAAIhBCmQgFANgFAJQgFAJgEAFQgHAFgIADQgHADgLgBQgLABgJgDg");
	this.shape_10.setTransform(-31.4,52.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeBOQgXgKgLgIIARgaQANAKAOAFQAOAGAKAAQANAAAGgFQAHgFAAgIIAAgBQAAgIgLgGQgGgDgRgGQgagHgJgGQgIgFgEgIQgEgIgBgMIAAAAQABgMAEgJQAEgJAIgHQAIgGAKgEQAMgDAKAAQAOAAARAFQAPAFANAIIgOAbQgNgHgLgEQgNgEgJAAQgJAAgGAEQgHAFAAAHIAAABQAAAHAMAGIAXAKIASAGQALAEAGADQAIAGAEAHQAEAJABAKIAAABQgBANgEAKQgFAJgIAHQgJAGgKADQgLADgOAAQgPAAgSgGg");
	this.shape_11.setTransform(-48.5,49.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAjBTIAAhbQABgKgDgHQgCgIgFgEQgEgFgGgEQgHgCgJAAQgFAAgHADQgHACgFAGQgFAFgDAHQgCAJgBAIIAABbIglAAIAAiiIAlAAIAAAaQAKgNAKgIQAHgEAIgCQAFgCAKAAQAOAAALAFQAKAEAIAIQAHAJAEALQAEALAAAPIAABmg");
	this.shape_12.setTransform(-65.6,49.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbBOQgPgFgLgMQgMgLgGgQIgFgQIgCgSIAAAAQAAgRAGgPQAGgQALgLQALgMAOgGIAPgGIAPgBQAKAAAJABIAQAGQAJAFAPAOQAKAMAFAQQAFAQAAAQIgBAKIh2AAQABAKAEAIQAFAIAGAFQAGAGAIACQAIADAHAAQANAAALgFQAKgFAKgKIAWAUQgGAHgHAGQgHAFgIAEQgIAEgKADQgKACgLAAQgPAAgQgHgAAqgKQgBgKgEgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgGAAgIAEQgHADgGAGQgFAFgEAIQgDAIgBAKIBSAAIAAAAg");
	this.shape_13.setTransform(-84.6,49.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgbBOQgPgFgLgMQgMgLgGgQIgFgQIgCgSIAAAAQAAgRAGgPQAGgQALgLQALgMAOgGIAPgGIAPgBQAKAAAJABIAQAGQAJAFAPAOQAKAMAFAQQAFAQAAAQIgBAKIh2AAQABAKAEAIQAFAIAGAFQAGAGAIACQAIADAHAAQANAAALgFQAKgFAKgKIAWAUQgGAHgHAGQgHAFgIAEQgIAEgKADQgKACgLAAQgPAAgQgHgAAqgKQgBgKgEgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgGAAgIAEQgHADgGAGQgFAFgEAIQgDAIgBAKIBSAAIAAAAg");
	this.shape_14.setTransform(-103.3,49.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBBnQgJgDgGgFQgGgGgDgJQgEgKAAgNIAAhUIgVAAIAAggIAVAAIAAgtIAkAAIAAAtIAsAAIAAAgIgsAAIAABOQAAALAFAFQAFAFAKAAQAMAAALgGIAAAfQgHAEgIACQgJACgKAAQgLAAgGgCg");
	this.shape_15.setTransform(-119.2,47.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AglBRQgKgDgIgHQgJgGgEgKQgFgJAAgMIAAgBQAAgNAFgLQAFgJAJgFQAJgHAMgDQAMgEAOAAQASAAAaAHIAAgDQAAgIgDgHQgCgGgGgFQgFgEgHgDQgIgCgIAAQgMAAgMADQgKACgMAFIgLgeQAQgGAMgEQAQgDARAAQASAAANAEQAOAFAJAJQAJAJAEANQAFAMAAARIAABfIgmAAIAAgUQgJAKgMAGQgRAHgNAAQgLAAgLgDgAgOAHQgHACgFADQgFAEgCAFQgDAEAAAGIAAABQAAALAJAHQAJAGAOAAQAHAAAIgCQAIgDAGgFQAGgEADgHQADgGAAgHIAAgKQgXgGgOAAQgHAAgHABg");
	this.shape_16.setTransform(-144.2,49.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgpBnQgSgFgQgKIAOgcQAOAJANAEQAPAFAQAAQALAAAKgEQAJgDAHgGQAGgGAEgKQADgJAAgNIAAgMQgPAQgJAFQgHAEgIACQgIADgJAAQgOAAgNgFQgOgGgKgKQgLgKgGgOQgGgMAAgSIAAAAQAAgNAGgUQAGgOALgKQAKgKAOgFQANgFAOAAQAJAAAIACQAIACAIAEQAMAHALAMIAAgYIAlAAIAACAQAAAVgFAPQgFAQgLAKQgFAGgHAEQgHAEgJADQgYAFgNAAQgUAAgTgFgAgRhJQgIAEgHAGQgGAGgEAIQgDAIAAAKIAAABQAAAKADAIQAEAIAGAFQAHAGAIADQAJADAIAAQAJAAAJgDQAIgDAHgGQAHgFADgIQAEgIAAgKIAAAAQAAgKgEgJQgDgIgHgGQgHgGgIgDQgJgEgJAAQgIAAgJADg");
	this.shape_17.setTransform(142,20.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAkBTIAAhbQAAgJgDgIQgCgIgEgFQgFgFgHgDQgGgCgIAAQgGAAgIADQgGACgFAGQgFAFgDAIQgCAIAAAIIAABbIgmAAIAAihIAmAAIAAAZQAIgNAMgIQAGgDAHgDQAHgCAIAAQAOAAALAFQALADAHAJQAIAIAEAMQAEAMAAAOIAABmg");
	this.shape_18.setTransform(122.6,18.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgRBwIAAiiIAkAAIAACigAgThLIAAgkIAnAAIAAAkg");
	this.shape_19.setTransform(108.4,15.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAjBxIAAhdQAAgKgCgHQgCgGgFgFQgEgFgGgDQgHgCgJAAQgFAAgIADQgGACgFAGQgFAFgDAFQgCAIAAAJIAABdIgmAAIAAjhIAmAAIAABZQAIgOALgHQAHgEAIgCQAFgCAKAAQAOAAAKAEQALAEAHAJQAIAIAEAMQAEALAAANIAABog");
	this.shape_20.setTransform(94.5,15.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgBBnQgJgDgGgFQgGgGgDgJQgEgJAAgOIAAhUIgVAAIAAggIAVAAIAAgtIAkAAIAAAtIAsAAIAAAgIgsAAIAABPQAAAKAFAFQAFAFAKAAQAMAAALgGIAAAfQgHAEgIACQgJACgKAAQgLAAgGgCg");
	this.shape_21.setTransform(78.3,16.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag3BoQgIgDgJgFIANgcQALAHALAAQAIAAAFgEQAFgEAFgLIhEihIAnAAIAtB3IAqh3IAoAAIhCClQgEANgGAJQgFAJgFAFQgGAFgIADQgHACgLAAQgLAAgKgCg");
	this.shape_22.setTransform(62.9,21.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AguBTIAAihIAlAAIAAAkQAEgJAFgHQAEgIAHgFQAIgGAJgCQAJgDAKAAIAAAoIgCAAQgMAAgKAEQgLAEgHAIQgGAIgEANQgEAKAAAQIAAA+g");
	this.shape_23.setTransform(48,18.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgbBOQgPgFgLgMQgMgLgGgPIgFgRIgCgSIAAAAQAAgQAGgQQAGgQALgLQALgMAOgGIAPgGIAPgBQAKAAAJABIAQAGQAJAEAPAPQAKAMAFAQQAFAQAAAQIgBAKIh2AAQABALAEAHQAFAIAGAGQAGAEAIADQAIADAHAAQANAAALgFQAKgFAKgJIAWATQgGAHgHAFQgHAHgIADQgIAFgKACQgKACgLAAQgPAAgQgHgAAqgKQgBgJgEgIQgDgIgFgGQgFgGgHgDQgIgDgJAAQgGAAgIADQgHADgGAGQgFAFgEAIQgDAIgBAKIBSAAIAAAAg");
	this.shape_24.setTransform(31.5,18.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgPBSIhDijIAoAAIAqB2IAsh2IAnAAIhCCjg");
	this.shape_25.setTransform(13,18.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbBOQgPgFgLgMQgMgLgGgPIgFgRIgCgSIAAAAQAAgQAGgQQAGgQALgLQALgMAOgGIAPgGIAPgBQAKAAAJABIAQAGQAJAEAPAPQAKAMAFAQQAFAQAAAQIgBAKIh2AAQABALAEAHQAFAIAGAGQAGAEAIADQAIADAHAAQANAAALgFQAKgFAKgJIAWATQgGAHgHAFQgHAHgIADQgIAFgKACQgKACgLAAQgPAAgQgHgAAqgKQgBgJgEgIQgDgIgFgGQgFgGgHgDQgIgDgJAAQgGAAgIADQgHADgGAGQgFAFgEAIQgDAIgBAKIBSAAIAAAAg");
	this.shape_26.setTransform(-5.6,18.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgeBOQgYgKgKgIIARgaQANAKAOAFQAOAGALAAQALAAAIgFQAGgFAAgIIAAgBQAAgIgLgGQgGgDgRgGQgZgHgKgGQgIgFgEgIQgEgIAAgMIAAAAQAAgMAEgJQAEgJAJgHQAHgGALgEQAKgDAKAAQAPAAARAFQAPAFANAIIgOAbQgNgHgLgEQgNgEgJAAQgJAAgHAEQgFAFAAAHIAAABQAAAHALAGIAYAKIASAGQAKAEAGADQAIAGAEAHQAFAJgBAKIAAABQABANgFAKQgFAJgIAHQgJAGgLADQgKADgNAAQgQAAgSgGg");
	this.shape_27.setTransform(-32.2,18.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgbBOQgPgFgLgMQgMgLgGgPIgFgRIgCgSIAAAAQAAgQAGgQQAGgQALgLQALgMAOgGIAPgGIAPgBQAKAAAJABIAQAGQAJAEAPAPQAKAMAFAQQAFAQAAAQIgBAKIh2AAQABALAEAHQAFAIAGAGQAGAEAIADQAIADAHAAQANAAALgFQAKgFAKgJIAWATQgGAHgHAFQgHAHgIADQgIAFgKACQgKACgLAAQgPAAgQgHgAAqgKQgBgJgEgIQgDgIgFgGQgFgGgHgDQgIgDgJAAQgGAAgIADQgHADgGAGQgFAFgEAIQgDAIgBAKIBSAAIAAAAg");
	this.shape_28.setTransform(-49.1,18.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAhBxIgvhHIgYAYIAAAvIglAAIAAjhIAlAAIAACGIBDhHIAtAAIhBBBIBDBhg");
	this.shape_29.setTransform(-66.4,15.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AglBRQgKgDgIgHQgJgGgEgKQgFgJAAgMIAAgBQAAgNAFgLQAFgJAJgFQAJgHAMgDQAMgEAOAAQASAAAaAHIAAgDQAAgIgDgHQgCgGgGgFQgFgEgHgDQgIgCgIAAQgMAAgMADQgKACgMAFIgLgeQAQgGAMgEQAQgDARAAQASAAANAEQAOAFAJAJQAJAJAEANQAFAMAAARIAABfIgmAAIAAgUQgJAKgMAGQgRAHgNAAQgLAAgLgDgAgOAHQgHACgFADQgFAEgCAFQgDAEAAAGIAAABQAAALAJAHQAJAGAOAAQAHAAAIgCQAIgDAGgFQAGgEADgHQADgGAAgHIAAgKQgXgGgOAAQgHAAgHABg");
	this.shape_30.setTransform(-85.9,18.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABXBTIAAhbQAAgJgCgIQgDgIgEgFQgFgFgFgDQgHgCgIAAQgHAAgHACQgGADgFAFQgFAFgCAIQgCAIgBAJIAABbIgjAAIAAhbQAAgKgCgHQgDgIgEgFQgEgFgGgDQgHgCgIAAQgHAAgGADQgHACgEAGQgGAGgCAHQgDAIAAAJIAABaIglAAIAAihIAlAAIAAAYQAKgNAKgHQAHgDAGgDQAIgCAJAAQAJAAAIACQAHACAGAEQAGADADAGQAFAFADAHQALgOAMgHQAIgEAIgCQAHgCAKAAQANAAAKAEQAMAEAGAIQAIAJAEALQAEAMAAAOIAABng");
	this.shape_31.setTransform(-109.2,18.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgBBnQgJgDgGgFQgGgGgDgJQgEgJAAgOIAAhUIgVAAIAAggIAVAAIAAgtIAkAAIAAAtIAsAAIAAAgIgsAAIAABPQAAAKAFAFQAFAFAKAAQAMAAALgGIAAAfQgHAEgIACQgJACgKAAQgLAAgGgCg");
	this.shape_32.setTransform(-139.9,16.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgSBsIAAjXIAlAAIAADXg");
	this.shape_33.setTransform(-150.9,15.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,0,337,65.9);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape.setTransform(148.9,42.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgRAzQgKgEgHgIQgIgHgEgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCQAGAAAGACIAKADQAGADAKAJQAGAIAEALQACAKAAAJIAAAHIhMAAQABAGADAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgEgCQgGgCgFAAQgEAAgFACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_1.setTransform(140.3,38.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgSAyQgQgGgHgGIALgQQAJAGAJAEQAJADAGAAQAIAAAEgDQAEgDAAgFIAAgBQAAgFgHgEIgOgGQgRgEgGgEQgEgDgEgFQgCgFAAgIQAAgHACgGQADgGAGgFQAFgEAGgCQAHgCAGAAQAKAAAKADQAKADAJAGIgKARQgHgFgIgCQgIgDgGAAQgFAAgEADQgEADAAAFIAAAAQAAAFAHAEIAPAGIALAEIALAEQAFAEACAFQADAFABAHIAAAAQgBAIgDAHQgCAGgGAEQgFAEgHACQgHACgJAAQgJAAgLgEg");
	this.shape_2.setTransform(129.1,38.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgXA0QgHgCgFgEQgGgEgDgGQgCgGAAgIIAAgBQAAgJACgGQAEgGAFgDQAHgEAHgDQAIgCAKAAQAKABARAEIAAgCQgBgGgBgEQgCgEgDgDQgEgCgFgCQgEgCgEABQgJgBgIACQgGACgHADIgHgUIASgGQAKgCAKAAQAMAAAJADQAIADAGAGQAFAGADAHQADAJABAKIAAA9IgYAAIAAgNQgHAHgIAEQgKAEgIAAQgIAAgGgCgAgJAEIgHAEIgFAFQgBADAAAEIAAABQAAAGAFAFQAGAEAJAAQAEAAAFgCQAFgBAEgDQAEgDACgEQACgFAAgEIAAgGQgPgEgJgBIgJABg");
	this.shape_3.setTransform(118.1,38.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AAXBJIAAg9QAAgGgCgFQgBgCgDgEQgDgDgEgBQgEgDgGAAQgDAAgEADQgFACgDACQgDAEgCADQgBAFgBAGIAAA8IgYAAIAAiQIAYAAIAAA4QAGgJAIgDQADgEAFgBQADgBAHAAQAIAAAIACQAGADAFAGQAFAFADAIQACAHAAAHIAABEg");
	this.shape_4.setTransform(106.4,36.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDIAJgCQAIAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgFAFQgEAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEADAGAAQAIAAAIgEQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_5.setTransform(94.5,38.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgdA1IAAhnIAYAAIAAAXQACgGADgEQADgFAEgEQAFgDAFgCQAGgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_6.setTransform(85.1,38.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgYAzQgIgDgEgGQgFgFgDgHQgCgIAAgJIAAhBIAYAAIAAA6QAAAGABAFQACAEADAEQADADAEACQAEABAFAAQAEAAAEgBQAFgCADgEQADgDACgFQABgFAAgGIAAg5IAZAAIAABnIgZAAIAAgQQgFAIgHAFQgFADgEABQgEABgGAAQgIAAgHgCg");
	this.shape_7.setTransform(74.2,38.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("Ag1BFIAAiHIAYAAIAAARQAHgJAIgEQAEgEAFgBQAFgBAFAAQAJAAAJADQAJAEAHAHQAHAIAEAJQAEAPAAAJIAAAAIgBAMIgDAJQgEAKgHAIQgHAGgJAEQgIADgKAAQgFABgFgCQgFgBgFgDQgIgEgGgJIAAAwgAgKgtQgGACgEAFQgFAEgCAGQgCAHAAAIIAAAAQAAAIACAFQACAFAFAFQAEAEAGADQAFACAFAAQAGAAAFgCQAGgDAEgEQAEgFACgFQADgFAAgIIAAAAQAAgIgDgHQgCgGgEgEQgFgFgFgCQgGgCgFgBQgFABgFACg");
	this.shape_8.setTransform(61.6,40.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AgjBDQgFgCgGgDIAIgSQAIAEAGAAQAGAAADgDQAEgDACgGIgshnIAaAAIAcBMIAchMIAZAAIgqBqQgDAIgEAFQgDAHgCADQgEADgGACQgEABgHAAQgHAAgHgBg");
	this.shape_9.setTransform(42.7,40.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQACgFAFgEQAFgDAGgCQAGgCAGABIAAAZIgBAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_10.setTransform(33.1,38.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgRAzQgJgEgIgIQgIgHgDgKIgEgKIgBgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCQAGAAAGACIAKADQAGADAKAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_11.setTransform(22.5,38.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AgJA1IgshpIAaAAIAbBMIAchMIAaAAIgrBpg");
	this.shape_12.setTransform(10.5,38.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgRAzQgJgEgIgIQgHgHgEgKIgEgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCQAGAAAGACIAKADQAGADAKAJQAGAIADALQADAKABAJIgBAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAHgDQAHgDAGgHIAPANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgEgEQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_13.setTransform(-1.4,38.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AAXA2IAAg7QAAgGgCgFQgBgEgDgEQgDgDgEgBQgEgDgGAAQgDAAgEADQgFACgDACQgDAEgCAFQgBAFgBAGIAAA6IgYAAIAAhoIAYAAIAAAQQAGgJAIgDQADgEAFgBQADgBAHAAQAIAAAIACQAGADAFAGQAFAFADAIQACAHAAAJIAABCg");
	this.shape_14.setTransform(-19.6,38.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAFQAFAEAGADQAGADAFAAQAHAAAGgDQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_15.setTransform(-32.4,38.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AAcBEQgGgDgEgEQgEgFgDgGQgCgHAAgIQAAgHACgGQADgHAEgFQAFgFAGgDQAGgCAHAAQAHAAAHACQAFADAFAFQAEAFADAHQACAFAAAIIAAAAQAAAIgCAGQgDAHgEAFQgFAEgGADQgGADgHAAQgHAAgHgDgAAfAVQgEAFAAAJIAAAAQAAAJAEAGQAEAGAHgBQAHABAEgGQAEgGAAgJQAAgJgEgFQgFgGgGAAQgHAAgEAGgAg7BGIBkiLIAUAAIhlCLgAg2gBQgGgDgFgFQgEgFgCgGQgDgHAAgHIAAgBQAAgGADgHQACgGAFgGQAEgEAGgEQAGgCAIAAQAHAAAGACQAGAEAEAEQAFAFACAHQACAGAAAHQAAAIgCAHQgCAGgFAFQgEAFgGADQgHABgHAAQgHAAgGgBgAg0gwQgEAFAAAIQAAAKAEAFQAFAGAHAAQAGAAAFgGQAEgGAAgIIAAgBQAAgIgFgFQgEgHgHABQgHgBgEAHg");
	this.shape_16.setTransform(-53.5,37);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgOBFQgHgBgHgDQgFgDgHgEIgKgJIAPgSQAJAJAJAEQAIAEAJAAQAGAAAFgBIAJgFQADgEACgEQACgFAAgFIAAAAQAAgGgDgEQgBgEgEgDQgEgDgFgCQgGgCgEAAQgHAAgHACIgMAFIgPgIIAEhFIBSAAIAAAWIg8AAIgCAhIAKgDIAJgBQALAAAIADQAKACAGAGQAHAFADAHQAEAIAAALIAAAAQAAALgEAJQgDAIgHAHQgHAGgKADQgJAEgLAAQgHAAgHgCg");
	this.shape_17.setTransform(-68.2,37.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgxBHIAAgUIAwgpQAHgIALgKIAFgJIABgIQAAgFgCgFQgBgEgDgDIgIgEQgEgBgFAAIgHABQgDABgFADQgGAEgJAMIgRgOQAFgIAFgEQAGgGAFgEQAHgEAGgCQAIgCAHAAQAKAAAJADQAJADAGAGQAGAGADAHQADAIAAAKQAAAIgCAGQgBAHgGAGQgDAEgIAHIgQAOIgbAYIBBAAIAAAWg");
	this.shape_18.setTransform(-80.5,36.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_19.setTransform(-89.3,42.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AACBGIAAhyIgXAHIgFgUIAkgMIARAAIAACLg");
	this.shape_20.setTransform(-96.6,37);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AAXA2IAAg7QAAgGgCgFQgBgEgDgEQgDgDgEgBQgEgDgGAAQgDAAgEADQgFACgDACQgDAEgCAFQgBAFgBAGIAAA6IgYAAIAAhoIAYAAIAAAQQAGgJAHgDQAFgEAEgBQADgBAHAAQAIAAAHACQAHADAFAGQAFAFADAIQACAHAAAJIAABCg");
	this.shape_21.setTransform(-112,38.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_22.setTransform(-121.9,38.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AgXA0QgHgCgFgEQgFgEgDgGQgEgGAAgIIAAgBQAAgJAEgGQADgGAGgDQAFgEAIgDQAIgCAJAAQALABAQAEIAAgCQAAgGgBgEQgCgEgDgDQgDgCgFgCQgFgCgFABQgIgBgHACQgHACgIADIgHgUIASgGQALgCAKAAQALAAAJADQAJADAGAGQAFAGAEAHQACAJAAAKIAAA9IgYAAIAAgNQgGAHgHAEQgLAEgIAAQgIAAgGgCgAgIAEIgIAEIgFAFQgBADgBAEIAAABQAAAGAHAFQAFAEAJAAQAEAAAFgCQAFgBAEgDQAEgDACgEQACgFAAgEIAAgGQgPgEgJgBIgIABg");
	this.shape_23.setTransform(-132.6,38.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AgzBGIAAiLIBmAAIAAAXIhNAAIAAAkIBEAAIAAAUIhEAAIAAAlIBOAAIAAAXg");
	this.shape_24.setTransform(-144.5,37);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_25.setTransform(135.8,20.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AgXBGQgIgDgHgIQgHgHgEgKIgDgLIgBgMIAAAAQAAgJAEgNQAEgJAHgIQAGgHAJgDQAJgEAKgBQAEABAFACQAGABAEACQAIAFAHAJIAAg6IAYAAIAACQIgYAAIAAgRQgHAJgIAFIgKAEQgFACgEAAQgJAAgKgEgAgKgLQgGADgEAEQgEAEgCAFQgDAGAAAIIAAAAQAAAIADAGQACAGAEAEQAEAFAGACQAFACAFAAQAFAAAGgCQAFgCAFgFQAFgEACgHQACgFAAgIIAAAAQAAgIgCgGQgCgFgFgEQgFgEgFgDQgGgDgFABQgFgBgFADg");
	this.shape_26.setTransform(126.2,14.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("AgeA1IAAhnIAZAAIAAAXQACgGADgEQACgFAFgEQAFgDAFgCQAGgCAIABIAAAZIgCAAQgIAAgHADQgGACgFAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_27.setTransform(116.1,16.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E7E").s().p("AgXA0QgHgCgFgEQgFgFgDgGQgEgFAAgIIAAgBQAAgJAEgGQADgGAGgDQAFgEAIgCQAIgCAJAAQALgBAQAFIAAgCQABgGgCgDQgCgFgDgDQgDgDgFgBQgFgCgFAAQgIAAgHACQgHABgHAEIgIgUIASgGQALgCAKAAQALAAAJADQAJADAGAFQAGAGADAJQADAIAAAKIAAA9IgZAAIAAgNQgGAHgHAEQgLAEgIAAQgIAAgGgCgAgJAFIgHADIgFAFQgCADABAEIAAAAQgBAIAHAEQAFAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJABIgJABg");
	this.shape_28.setTransform(105.4,16.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E7E").s().p("AgGBHIgOgFIgMgHIgLgIIgIgLIgHgMIgDgOIgBgOIAAAAIABgNIADgNQADgHAEgGIAIgLIALgJQAGgDAHgDQAGgDAHgBQAGgCAIAAQAJAAAIACQAIABAGADQAKAEAOAMIgRASQgJgJgJgDQgEgDgFgBIgLgCQgJAAgIAFQgJAEgGAGQgGAHgEAJQgDAJAAAJIAAAAQAAAJADAKQAEAJAGAHQAGAGAJAFQAIADAJAAQAFABAGgCQAGgBAEgCQAIgFAKgJIARAQIgMAKQgGAFgHADQgHAEgHABQgJACgJAAQgHAAgGgBg");
	this.shape_29.setTransform(92.6,15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E7E").s().p("AAVBIIgegtIgOAPIAAAeIgZAAIAAiQIAZAAIAABWIApgtIAeAAIgrApIAsA+g");
	this.shape_30.setTransform(73.9,14.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E7E").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDIAJgCQAIAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgFAFQgEAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEADAGAAQAIAAAIgEQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_31.setTransform(61.8,16.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E7E").s().p("AgXA0QgHgCgFgEQgGgFgDgGQgDgFAAgIIAAgBQAAgJADgGQAEgGAFgDQAHgEAHgCQAIgCAKAAQAKgBAQAFIAAgCQABgGgCgDQgCgFgDgDQgDgDgGgBQgEgCgFAAQgIAAgIACQgGABgHAEIgIgUIASgGQALgCAKAAQALAAAKADQAIADAGAFQAFAGADAJQAEAIAAAKIAAA9IgZAAIAAgNQgFAHgIAEQgLAEgIAAQgHAAgHgCgAgJAFIgHADIgFAFQgCADABAEIAAAAQAAAIAFAEQAGAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJABIgJABg");
	this.shape_32.setTransform(49.9,16.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E7E").s().p("Ag5BFIAAiJIA9AAQAMAAAJACQAKAEAGAGQAEAEADAGQACAGAAAHIAAABQAAAFgCAFQgBAFgDAEQgFAHgJAEIALAEIAJAHQAEAEACAFQACAGAAAGIAAABQAAAJgEAHQgDAIgHAEQgHAFgKADQgJACgMAAgAghAvIAnAAIAMAAQAFgCADgCQAEgCABgEQACgEAAgEIAAgBQAAgEgCgEQgBgEgEgCIgJgDIgNgBIglAAgAghgKIAhAAIAKgBIAIgDQAEgDACgDQABgEAAgFIAAAAQAAgEgBgEIgFgFIgIgEIgKgBIgiAAg");
	this.shape_33.setTransform(37.5,15);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E7E").s().p("AAXBIIAAg7QAAgHgBgEQgCgDgDgDQgDgEgEgCQgEgBgGAAQgDAAgFABQgEACgDAEQgDADgCADQgBAFAAAGIAAA7IgZAAIAAiQIAZAAIAAA6QAFgKAHgEQAEgCAFgBQADgCAGgBQAKABAGADQAHADAFAFQAFAFACAHQADAIAAAIIAABCg");
	this.shape_34.setTransform(17.8,14.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E7E").s().p("AgTAyQgPgGgGgGIAKgQQAJAGAJAEQAJADAGAAQAIAAAEgDQAEgDABgFIAAgBQAAgFgIgEIgOgGQgRgEgFgEQgGgDgCgFQgDgFAAgIQAAgHADgGQADgGAFgFQAFgEAGgCQAIgCAGAAQAJAAALADQAKADAIAGIgJARQgIgFgIgCQgHgDgHAAQgFAAgEADQgEADAAAFIAAAAQAAAFAHAEIAPAGIAMAEIAKAEQAFAEADAFQACAFAAAHIAAAAQAAAIgCAHQgEAGgFAEQgFAEgHACQgHACgIAAQgKAAgMgEg");
	this.shape_35.setTransform(6.4,16.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E7E").s().p("AgXA0QgHgCgFgEQgFgFgDgGQgDgFAAgIIAAgBQAAgJADgGQADgGAGgDQAFgEAIgCQAIgCAJAAQALgBARAFIAAgCQAAgGgCgDQgCgFgDgDQgEgDgEgBQgFgCgEAAQgJAAgHACQgHABgIAEIgGgUIASgGQAKgCAKAAQALAAAJADQAJADAGAFQAGAGADAJQACAIAAAKIAAA9IgXAAIAAgNQgGAHgJAEQgKAEgIAAQgHAAgHgCgAgIAFIgIADIgFAFQgBADgBAEIAAAAQAAAIAHAEQAFAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJABIgIABg");
	this.shape_36.setTransform(-4.6,16.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E7E").s().p("AgGBHIgOgFIgMgHIgLgIIgIgLIgGgMIgFgOIgBgOIAAAAIABgNIAFgNQACgHAEgGIAIgLIALgJQAGgDAHgDQAGgDAHgBQAGgCAHAAQAKAAAIACQAIABAHADQAIAEAOAMIgQASQgIgJgKgDQgEgDgGgBIgLgCQgIAAgJAFQgIAEgGAGQgGAHgEAJQgDAJAAAJIAAAAQAAAJADAKQAEAJAGAHQAGAGAIAFQAJADAIAAQAGABAGgCQAFgBAGgCQAHgFALgJIAPAQIgLAKQgGAFgHADQgGAEgJABQgIACgKAAQgGAAgGgBg");
	this.shape_37.setTransform(-17.3,15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E7E").s().p("AgXBGQgIgDgHgIQgHgHgEgKIgDgLIgBgMIAAAAQAAgJAEgNQAEgJAHgIQAHgHAIgDQAJgEAKgBQAEABAGACQAFABAFACQAHAFAHAJIAAg6IAYAAIAACQIgYAAIAAgRQgHAJgHAFIgKAEQgGACgEAAQgJAAgKgEgAgKgLQgGADgEAEQgEAEgCAFQgDAGAAAIIAAAAQAAAIADAGQACAGAFAEQAEAFAFACQAGACAEAAQAFAAAGgCQAFgCAFgFQAEgEACgHQADgFAAgIIAAAAQAAgIgDgGQgCgFgEgEQgFgEgFgDQgGgDgFABQgEgBgGADg");
	this.shape_38.setTransform(-37.9,14.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E7E").s().p("AAXA1IAAg5QAAgHgCgEQgBgFgDgDQgDgEgEgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFQgCAFAAAGIAAA5IgYAAIAAhnIAYAAIAAARQAGgKAIgEQADgCAFgBQAEgCAFgBQAJABAIADQAGADAFAFQAFAFADAHQACAIAAAKIAABAg");
	this.shape_39.setTransform(-50.5,16.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E7E").s().p("AgZAzQgGgDgFgGQgFgFgDgHQgCgIAAgJIAAhBIAYAAIAAA6QAAAGACAFQABAEADAEQADADAEACQAFABAEAAQAEAAAEgBQAFgCADgEQADgDACgFQACgFAAgGIAAg5IAYAAIAABnIgYAAIAAgQQgGAIgIAFQgEADgFABQgDABgFAAQgJAAgIgCg");
	this.shape_40.setTransform(-63,16.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E7E").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAFQAFAEAGADQAGADAFAAQAHAAAGgDQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_41.setTransform(-75.7,16.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003E7E").s().p("AgKBGIgPgEIgOgHIgOgKIAPgSQAHAHAOAHQAFACAGABIAKABIALgBIAHgDQAEgDABgDQACgDAAgEIAAgBQAAgEgBgCIgFgFQgDgDgHgCIgNgEIgUgHQgJgDgGgDQgGgFgDgGQgDgHAAgKIAAAAQAAgJAEgIQADgHAGgFQAHgGAJgDQAIgCAKAAIANABIANADQAJADAPAKIgOATQgJgIgKgDQgJgDgIgBIgJABIgHAEQgGAFAAAHIAAAAIABAIIAFAFQAEADAGACIAPAEQALADAIADQAJAEAFADQAGAEADAHQADAGAAAKQAAAJgEAIQgDAIgHAFQgHAGgJACQgJAEgLAAIgOgCg");
	this.shape_42.setTransform(-88.8,15);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003E7E").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgDgKIAAgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgGACQgEACgDAEIgGAJQgDAFAAAGIA0AAIAAAAg");
	this.shape_43.setTransform(-107,16.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#003E7E").s().p("AAXBIIAAg7QAAgHgCgEQgBgDgDgDQgDgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCADQgCAFAAAGIAAA7IgYAAIAAiQIAYAAIAAA6QAGgKAIgEQAEgCAEgBQAEgCAFgBQAJABAIADQAGADAFAFQAFAFACAHQADAIAAAIIAABCg");
	this.shape_44.setTransform(-119.2,14.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#003E7E").s().p("AgLBFIAAhzIgsAAIAAgWIBvAAIAAAWIgsAAIAABzg");
	this.shape_45.setTransform(-132,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-162,4,324,46);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A6P13MA0fAAAMAAAArvMg0fAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-169,-141,338,282);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201703_Teensy_336x280_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(316,145,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.setTransform(67,267.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.setTransform(267,265.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border336x280();
	this.instance_2.setTransform(168.5,140.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_80 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_81 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_82 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_83 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_84 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_85 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_86 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_87 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_88 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_89 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_169 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_170 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_171 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_172 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_173 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_174 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_175 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_176 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_177 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_178 = new cjs.Graphics().p("A6PM5IAA57MA0eAAAIAAZ7g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(80).to({graphics:mask_graphics_80,x:168,y:83}).wait(1).to({graphics:mask_graphics_81,x:168,y:77.4}).wait(1).to({graphics:mask_graphics_82,x:168,y:71.9}).wait(1).to({graphics:mask_graphics_83,x:168,y:66.3}).wait(1).to({graphics:mask_graphics_84,x:168,y:60.8}).wait(1).to({graphics:mask_graphics_85,x:168,y:55.2}).wait(1).to({graphics:mask_graphics_86,x:168,y:49.7}).wait(1).to({graphics:mask_graphics_87,x:168,y:44.1}).wait(1).to({graphics:mask_graphics_88,x:168,y:38.6}).wait(1).to({graphics:mask_graphics_89,x:168,y:33}).wait(80).to({graphics:mask_graphics_169,x:168,y:33}).wait(1).to({graphics:mask_graphics_170,x:168,y:20}).wait(1).to({graphics:mask_graphics_171,x:168,y:7}).wait(1).to({graphics:mask_graphics_172,x:168,y:-6}).wait(1).to({graphics:mask_graphics_173,x:168,y:-19}).wait(1).to({graphics:mask_graphics_174,x:168,y:-32}).wait(1).to({graphics:mask_graphics_175,x:168,y:-45}).wait(1).to({graphics:mask_graphics_176,x:168,y:-58}).wait(1).to({graphics:mask_graphics_177,x:168,y:-71}).wait(1).to({graphics:mask_graphics_178,x:168,y:-83.5}).wait(4).to({graphics:null,x:0,y:0}).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.setTransform(150,57,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({y:-60},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.setTransform(168,175,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:126},9).wait(80).to({y:9},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.setTransform(288.5,203,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({y:153},9).wait(80).to({y:37},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_6 = new lib.CTA();
	this.instance_6.setTransform(287.5,233,1,1,0,0,0,119.5,40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).wait(79).to({y:118},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(169).to({scaleY:1,y:-2},9).to({_off:true},4).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.setTransform(168,244.1,1.5,1.5,0,0,0,0,2.6);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.setTransform(484.3,253,1.47,1.47,0,0,0,215.2,63.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.setTransform(291.9,228.5,1.52,1.52,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.setTransform(150,92.2,1,2,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},182).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.setTransform(166.5,266.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(167,140,338,281);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;